System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: "ts",
  typescriptOptions: {
    "tsconfig": true
  },
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  bundles: {
    ".dev/vendor.js": [
      "npm:zone.js@0.6.12.js",
      "npm:zone.js@0.6.12/dist/zone.js",
      "github:jspm/nodelibs-process@0.1.2.js",
      "github:jspm/nodelibs-process@0.1.2/index.js",
      "npm:process@0.11.5.js",
      "npm:process@0.11.5/browser.js",
      "npm:rxjs@5.0.0-beta.9/Rx.js",
      "npm:symbol-observable@0.2.4.js",
      "npm:symbol-observable@0.2.4/index.js",
      "npm:symbol-observable@0.2.4/ponyfill.js",
      "npm:rxjs@5.0.0-beta.9/symbol/iterator.js",
      "npm:rxjs@5.0.0-beta.9/util/root.js",
      "npm:rxjs@5.0.0-beta.9/symbol/rxSubscriber.js",
      "npm:rxjs@5.0.0-beta.9/scheduler/animationFrame.js",
      "npm:rxjs@5.0.0-beta.9/scheduler/AnimationFrameScheduler.js",
      "npm:rxjs@5.0.0-beta.9/scheduler/AnimationFrameAction.js",
      "npm:rxjs@5.0.0-beta.9/util/AnimationFrame.js",
      "npm:rxjs@5.0.0-beta.9/scheduler/FutureAction.js",
      "npm:rxjs@5.0.0-beta.9/Subscription.js",
      "npm:rxjs@5.0.0-beta.9/util/UnsubscriptionError.js",
      "npm:rxjs@5.0.0-beta.9/util/errorObject.js",
      "npm:rxjs@5.0.0-beta.9/util/tryCatch.js",
      "npm:rxjs@5.0.0-beta.9/util/isFunction.js",
      "npm:rxjs@5.0.0-beta.9/util/isObject.js",
      "npm:rxjs@5.0.0-beta.9/util/isArray.js",
      "npm:rxjs@5.0.0-beta.9/scheduler/QueueScheduler.js",
      "npm:rxjs@5.0.0-beta.9/scheduler/QueueAction.js",
      "npm:rxjs@5.0.0-beta.9/scheduler/queue.js",
      "npm:rxjs@5.0.0-beta.9/scheduler/async.js",
      "npm:rxjs@5.0.0-beta.9/scheduler/AsyncScheduler.js",
      "npm:rxjs@5.0.0-beta.9/scheduler/asap.js",
      "npm:rxjs@5.0.0-beta.9/scheduler/AsapScheduler.js",
      "npm:rxjs@5.0.0-beta.9/scheduler/AsapAction.js",
      "npm:rxjs@5.0.0-beta.9/util/Immediate.js",
      "npm:rxjs@5.0.0-beta.9/observable/dom/AjaxObservable.js",
      "npm:rxjs@5.0.0-beta.9/Subscriber.js",
      "npm:rxjs@5.0.0-beta.9/Observer.js",
      "npm:rxjs@5.0.0-beta.9/Observable.js",
      "npm:rxjs@5.0.0-beta.9/util/toSubscriber.js",
      "npm:rxjs@5.0.0-beta.9/scheduler/VirtualTimeScheduler.js",
      "npm:rxjs@5.0.0-beta.9/testing/TestScheduler.js",
      "npm:rxjs@5.0.0-beta.9/testing/SubscriptionLog.js",
      "npm:rxjs@5.0.0-beta.9/testing/HotObservable.js",
      "npm:rxjs@5.0.0-beta.9/util/applyMixins.js",
      "npm:rxjs@5.0.0-beta.9/testing/SubscriptionLoggable.js",
      "npm:rxjs@5.0.0-beta.9/Subject.js",
      "npm:rxjs@5.0.0-beta.9/SubjectSubscription.js",
      "npm:rxjs@5.0.0-beta.9/util/ObjectUnsubscribedError.js",
      "npm:rxjs@5.0.0-beta.9/testing/ColdObservable.js",
      "npm:rxjs@5.0.0-beta.9/Notification.js",
      "npm:rxjs@5.0.0-beta.9/operator/timestamp.js",
      "npm:rxjs@5.0.0-beta.9/operator/timeInterval.js",
      "npm:rxjs@5.0.0-beta.9/util/ArgumentOutOfRangeError.js",
      "npm:rxjs@5.0.0-beta.9/util/EmptyError.js",
      "npm:rxjs@5.0.0-beta.9/observable/ConnectableObservable.js",
      "npm:rxjs@5.0.0-beta.9/observable/MulticastObservable.js",
      "npm:rxjs@5.0.0-beta.9/BehaviorSubject.js",
      "npm:rxjs@5.0.0-beta.9/util/throwError.js",
      "npm:rxjs@5.0.0-beta.9/ReplaySubject.js",
      "npm:rxjs@5.0.0-beta.9/operator/observeOn.js",
      "npm:rxjs@5.0.0-beta.9/AsyncSubject.js",
      "npm:rxjs@5.0.0-beta.9/Operator.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/zipAll.js",
      "npm:rxjs@5.0.0-beta.9/operator/zipAll.js",
      "npm:rxjs@5.0.0-beta.9/operator/zip.js",
      "npm:rxjs@5.0.0-beta.9/util/subscribeToResult.js",
      "npm:rxjs@5.0.0-beta.9/InnerSubscriber.js",
      "npm:rxjs@5.0.0-beta.9/util/isPromise.js",
      "npm:rxjs@5.0.0-beta.9/OuterSubscriber.js",
      "npm:rxjs@5.0.0-beta.9/observable/ArrayObservable.js",
      "npm:rxjs@5.0.0-beta.9/util/isScheduler.js",
      "npm:rxjs@5.0.0-beta.9/observable/EmptyObservable.js",
      "npm:rxjs@5.0.0-beta.9/observable/ScalarObservable.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/zip.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/withLatestFrom.js",
      "npm:rxjs@5.0.0-beta.9/operator/withLatestFrom.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/windowWhen.js",
      "npm:rxjs@5.0.0-beta.9/operator/windowWhen.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/windowToggle.js",
      "npm:rxjs@5.0.0-beta.9/operator/windowToggle.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/windowTime.js",
      "npm:rxjs@5.0.0-beta.9/operator/windowTime.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/windowCount.js",
      "npm:rxjs@5.0.0-beta.9/operator/windowCount.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/window.js",
      "npm:rxjs@5.0.0-beta.9/operator/window.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/toPromise.js",
      "npm:rxjs@5.0.0-beta.9/operator/toPromise.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/toArray.js",
      "npm:rxjs@5.0.0-beta.9/operator/toArray.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/timestamp.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/timeoutWith.js",
      "npm:rxjs@5.0.0-beta.9/operator/timeoutWith.js",
      "npm:rxjs@5.0.0-beta.9/util/isDate.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/timeout.js",
      "npm:rxjs@5.0.0-beta.9/operator/timeout.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/timeInterval.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/throttleTime.js",
      "npm:rxjs@5.0.0-beta.9/operator/throttleTime.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/throttle.js",
      "npm:rxjs@5.0.0-beta.9/operator/throttle.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/takeWhile.js",
      "npm:rxjs@5.0.0-beta.9/operator/takeWhile.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/takeUntil.js",
      "npm:rxjs@5.0.0-beta.9/operator/takeUntil.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/takeLast.js",
      "npm:rxjs@5.0.0-beta.9/operator/takeLast.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/take.js",
      "npm:rxjs@5.0.0-beta.9/operator/take.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/switchMapTo.js",
      "npm:rxjs@5.0.0-beta.9/operator/switchMapTo.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/switchMap.js",
      "npm:rxjs@5.0.0-beta.9/operator/switchMap.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/switch.js",
      "npm:rxjs@5.0.0-beta.9/operator/switch.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/subscribeOn.js",
      "npm:rxjs@5.0.0-beta.9/operator/subscribeOn.js",
      "npm:rxjs@5.0.0-beta.9/observable/SubscribeOnObservable.js",
      "npm:rxjs@5.0.0-beta.9/util/isNumeric.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/startWith.js",
      "npm:rxjs@5.0.0-beta.9/operator/startWith.js",
      "npm:rxjs@5.0.0-beta.9/operator/concat.js",
      "npm:rxjs@5.0.0-beta.9/operator/mergeAll.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/skipWhile.js",
      "npm:rxjs@5.0.0-beta.9/operator/skipWhile.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/skipUntil.js",
      "npm:rxjs@5.0.0-beta.9/operator/skipUntil.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/skip.js",
      "npm:rxjs@5.0.0-beta.9/operator/skip.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/single.js",
      "npm:rxjs@5.0.0-beta.9/operator/single.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/share.js",
      "npm:rxjs@5.0.0-beta.9/operator/share.js",
      "npm:rxjs@5.0.0-beta.9/operator/multicast.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/scan.js",
      "npm:rxjs@5.0.0-beta.9/operator/scan.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/sampleTime.js",
      "npm:rxjs@5.0.0-beta.9/operator/sampleTime.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/sample.js",
      "npm:rxjs@5.0.0-beta.9/operator/sample.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/retryWhen.js",
      "npm:rxjs@5.0.0-beta.9/operator/retryWhen.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/retry.js",
      "npm:rxjs@5.0.0-beta.9/operator/retry.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/repeat.js",
      "npm:rxjs@5.0.0-beta.9/operator/repeat.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/reduce.js",
      "npm:rxjs@5.0.0-beta.9/operator/reduce.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/race.js",
      "npm:rxjs@5.0.0-beta.9/operator/race.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/publishLast.js",
      "npm:rxjs@5.0.0-beta.9/operator/publishLast.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/publishReplay.js",
      "npm:rxjs@5.0.0-beta.9/operator/publishReplay.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/publishBehavior.js",
      "npm:rxjs@5.0.0-beta.9/operator/publishBehavior.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/publish.js",
      "npm:rxjs@5.0.0-beta.9/operator/publish.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/pluck.js",
      "npm:rxjs@5.0.0-beta.9/operator/pluck.js",
      "npm:rxjs@5.0.0-beta.9/operator/map.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/partition.js",
      "npm:rxjs@5.0.0-beta.9/operator/partition.js",
      "npm:rxjs@5.0.0-beta.9/operator/filter.js",
      "npm:rxjs@5.0.0-beta.9/util/not.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/pairwise.js",
      "npm:rxjs@5.0.0-beta.9/operator/pairwise.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/onErrorResumeNext.js",
      "npm:rxjs@5.0.0-beta.9/operator/onErrorResumeNext.js",
      "npm:rxjs@5.0.0-beta.9/observable/FromObservable.js",
      "npm:rxjs@5.0.0-beta.9/observable/ArrayLikeObservable.js",
      "npm:rxjs@5.0.0-beta.9/observable/IteratorObservable.js",
      "npm:rxjs@5.0.0-beta.9/observable/PromiseObservable.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/observeOn.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/multicast.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/min.js",
      "npm:rxjs@5.0.0-beta.9/operator/min.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/mergeScan.js",
      "npm:rxjs@5.0.0-beta.9/operator/mergeScan.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/mergeMapTo.js",
      "npm:rxjs@5.0.0-beta.9/operator/mergeMapTo.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/mergeMap.js",
      "npm:rxjs@5.0.0-beta.9/operator/mergeMap.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/mergeAll.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/merge.js",
      "npm:rxjs@5.0.0-beta.9/operator/merge.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/max.js",
      "npm:rxjs@5.0.0-beta.9/operator/max.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/materialize.js",
      "npm:rxjs@5.0.0-beta.9/operator/materialize.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/mapTo.js",
      "npm:rxjs@5.0.0-beta.9/operator/mapTo.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/map.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/every.js",
      "npm:rxjs@5.0.0-beta.9/operator/every.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/let.js",
      "npm:rxjs@5.0.0-beta.9/operator/let.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/last.js",
      "npm:rxjs@5.0.0-beta.9/operator/last.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/auditTime.js",
      "npm:rxjs@5.0.0-beta.9/operator/auditTime.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/audit.js",
      "npm:rxjs@5.0.0-beta.9/operator/audit.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/isEmpty.js",
      "npm:rxjs@5.0.0-beta.9/operator/isEmpty.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/ignoreElements.js",
      "npm:rxjs@5.0.0-beta.9/operator/ignoreElements.js",
      "npm:rxjs@5.0.0-beta.9/util/noop.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/groupBy.js",
      "npm:rxjs@5.0.0-beta.9/operator/groupBy.js",
      "npm:rxjs@5.0.0-beta.9/util/FastMap.js",
      "npm:rxjs@5.0.0-beta.9/util/Map.js",
      "npm:rxjs@5.0.0-beta.9/util/MapPolyfill.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/first.js",
      "npm:rxjs@5.0.0-beta.9/operator/first.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/findIndex.js",
      "npm:rxjs@5.0.0-beta.9/operator/findIndex.js",
      "npm:rxjs@5.0.0-beta.9/operator/find.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/find.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/finally.js",
      "npm:rxjs@5.0.0-beta.9/operator/finally.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/filter.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/elementAt.js",
      "npm:rxjs@5.0.0-beta.9/operator/elementAt.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/expand.js",
      "npm:rxjs@5.0.0-beta.9/operator/expand.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/exhaustMap.js",
      "npm:rxjs@5.0.0-beta.9/operator/exhaustMap.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/exhaust.js",
      "npm:rxjs@5.0.0-beta.9/operator/exhaust.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/do.js",
      "npm:rxjs@5.0.0-beta.9/operator/do.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/distinctUntilKeyChanged.js",
      "npm:rxjs@5.0.0-beta.9/operator/distinctUntilKeyChanged.js",
      "npm:rxjs@5.0.0-beta.9/operator/distinctUntilChanged.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/distinctUntilChanged.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/distinctKey.js",
      "npm:rxjs@5.0.0-beta.9/operator/distinctKey.js",
      "npm:rxjs@5.0.0-beta.9/operator/distinct.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/distinct.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/delayWhen.js",
      "npm:rxjs@5.0.0-beta.9/operator/delayWhen.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/delay.js",
      "npm:rxjs@5.0.0-beta.9/operator/delay.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/defaultIfEmpty.js",
      "npm:rxjs@5.0.0-beta.9/operator/defaultIfEmpty.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/debounceTime.js",
      "npm:rxjs@5.0.0-beta.9/operator/debounceTime.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/debounce.js",
      "npm:rxjs@5.0.0-beta.9/operator/debounce.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/dematerialize.js",
      "npm:rxjs@5.0.0-beta.9/operator/dematerialize.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/count.js",
      "npm:rxjs@5.0.0-beta.9/operator/count.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/concatMapTo.js",
      "npm:rxjs@5.0.0-beta.9/operator/concatMapTo.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/concatMap.js",
      "npm:rxjs@5.0.0-beta.9/operator/concatMap.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/concatAll.js",
      "npm:rxjs@5.0.0-beta.9/operator/concatAll.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/concat.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/combineLatest.js",
      "npm:rxjs@5.0.0-beta.9/operator/combineLatest.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/combineAll.js",
      "npm:rxjs@5.0.0-beta.9/operator/combineAll.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/catch.js",
      "npm:rxjs@5.0.0-beta.9/operator/catch.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/cache.js",
      "npm:rxjs@5.0.0-beta.9/operator/cache.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/bufferWhen.js",
      "npm:rxjs@5.0.0-beta.9/operator/bufferWhen.js",
      "github:jspm/nodelibs-buffer@0.1.0.js",
      "github:jspm/nodelibs-buffer@0.1.0/index.js",
      "npm:buffer@3.6.0.js",
      "npm:buffer@3.6.0/index.js",
      "npm:isarray@1.0.0.js",
      "npm:isarray@1.0.0/index.js",
      "npm:ieee754@1.1.6.js",
      "npm:ieee754@1.1.6/index.js",
      "npm:base64-js@0.0.8.js",
      "npm:base64-js@0.0.8/lib/b64.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/bufferToggle.js",
      "npm:rxjs@5.0.0-beta.9/operator/bufferToggle.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/bufferTime.js",
      "npm:rxjs@5.0.0-beta.9/operator/bufferTime.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/bufferCount.js",
      "npm:rxjs@5.0.0-beta.9/operator/bufferCount.js",
      "npm:rxjs@5.0.0-beta.9/add/operator/buffer.js",
      "npm:rxjs@5.0.0-beta.9/operator/buffer.js",
      "npm:rxjs@5.0.0-beta.9/add/observable/dom/webSocket.js",
      "npm:rxjs@5.0.0-beta.9/observable/dom/webSocket.js",
      "npm:rxjs@5.0.0-beta.9/observable/dom/WebSocketSubject.js",
      "npm:rxjs@5.0.0-beta.9/util/assign.js",
      "npm:rxjs@5.0.0-beta.9/add/observable/dom/ajax.js",
      "npm:rxjs@5.0.0-beta.9/observable/dom/ajax.js",
      "npm:rxjs@5.0.0-beta.9/add/observable/zip.js",
      "npm:rxjs@5.0.0-beta.9/observable/zip.js",
      "npm:rxjs@5.0.0-beta.9/add/observable/timer.js",
      "npm:rxjs@5.0.0-beta.9/observable/timer.js",
      "npm:rxjs@5.0.0-beta.9/observable/TimerObservable.js",
      "npm:rxjs@5.0.0-beta.9/add/observable/throw.js",
      "npm:rxjs@5.0.0-beta.9/observable/throw.js",
      "npm:rxjs@5.0.0-beta.9/observable/ErrorObservable.js",
      "npm:rxjs@5.0.0-beta.9/add/observable/using.js",
      "npm:rxjs@5.0.0-beta.9/observable/using.js",
      "npm:rxjs@5.0.0-beta.9/observable/UsingObservable.js",
      "npm:rxjs@5.0.0-beta.9/add/observable/range.js",
      "npm:rxjs@5.0.0-beta.9/observable/range.js",
      "npm:rxjs@5.0.0-beta.9/observable/RangeObservable.js",
      "npm:rxjs@5.0.0-beta.9/add/observable/onErrorResumeNext.js",
      "npm:rxjs@5.0.0-beta.9/add/observable/of.js",
      "npm:rxjs@5.0.0-beta.9/observable/of.js",
      "npm:rxjs@5.0.0-beta.9/add/observable/never.js",
      "npm:rxjs@5.0.0-beta.9/observable/never.js",
      "npm:rxjs@5.0.0-beta.9/observable/NeverObservable.js",
      "npm:rxjs@5.0.0-beta.9/add/observable/race.js",
      "npm:rxjs@5.0.0-beta.9/add/observable/merge.js",
      "npm:rxjs@5.0.0-beta.9/observable/merge.js",
      "npm:rxjs@5.0.0-beta.9/add/observable/interval.js",
      "npm:rxjs@5.0.0-beta.9/observable/interval.js",
      "npm:rxjs@5.0.0-beta.9/observable/IntervalObservable.js",
      "npm:rxjs@5.0.0-beta.9/add/observable/if.js",
      "npm:rxjs@5.0.0-beta.9/observable/if.js",
      "npm:rxjs@5.0.0-beta.9/observable/IfObservable.js",
      "npm:rxjs@5.0.0-beta.9/add/observable/generate.js",
      "npm:rxjs@5.0.0-beta.9/observable/GenerateObservable.js",
      "npm:rxjs@5.0.0-beta.9/add/observable/fromPromise.js",
      "npm:rxjs@5.0.0-beta.9/observable/fromPromise.js",
      "npm:rxjs@5.0.0-beta.9/add/observable/fromEventPattern.js",
      "npm:rxjs@5.0.0-beta.9/observable/fromEventPattern.js",
      "npm:rxjs@5.0.0-beta.9/observable/FromEventPatternObservable.js",
      "npm:rxjs@5.0.0-beta.9/add/observable/fromEvent.js",
      "npm:rxjs@5.0.0-beta.9/observable/fromEvent.js",
      "npm:rxjs@5.0.0-beta.9/observable/FromEventObservable.js",
      "npm:rxjs@5.0.0-beta.9/add/observable/from.js",
      "npm:rxjs@5.0.0-beta.9/observable/from.js",
      "npm:rxjs@5.0.0-beta.9/add/observable/forkJoin.js",
      "npm:rxjs@5.0.0-beta.9/observable/forkJoin.js",
      "npm:rxjs@5.0.0-beta.9/observable/ForkJoinObservable.js",
      "npm:rxjs@5.0.0-beta.9/add/observable/empty.js",
      "npm:rxjs@5.0.0-beta.9/observable/empty.js",
      "npm:rxjs@5.0.0-beta.9/add/observable/defer.js",
      "npm:rxjs@5.0.0-beta.9/observable/defer.js",
      "npm:rxjs@5.0.0-beta.9/observable/DeferObservable.js",
      "npm:rxjs@5.0.0-beta.9/add/observable/concat.js",
      "npm:rxjs@5.0.0-beta.9/observable/concat.js",
      "npm:rxjs@5.0.0-beta.9/add/observable/combineLatest.js",
      "npm:rxjs@5.0.0-beta.9/observable/combineLatest.js",
      "npm:rxjs@5.0.0-beta.9/add/observable/bindNodeCallback.js",
      "npm:rxjs@5.0.0-beta.9/observable/bindNodeCallback.js",
      "npm:rxjs@5.0.0-beta.9/observable/BoundNodeCallbackObservable.js",
      "npm:rxjs@5.0.0-beta.9/add/observable/bindCallback.js",
      "npm:rxjs@5.0.0-beta.9/observable/bindCallback.js",
      "npm:rxjs@5.0.0-beta.9/observable/BoundCallbackObservable.js",
      "npm:reflect-metadata@0.1.3.js",
      "npm:reflect-metadata@0.1.3/Reflect.js",
      "github:jspm/nodelibs-crypto@0.1.0.js",
      "github:jspm/nodelibs-crypto@0.1.0/index.js",
      "npm:crypto-browserify@3.11.0.js",
      "npm:crypto-browserify@3.11.0/index.js",
      "npm:public-encrypt@4.0.0.js",
      "npm:public-encrypt@4.0.0/browser.js",
      "npm:public-encrypt@4.0.0/privateDecrypt.js",
      "npm:public-encrypt@4.0.0/withPublic.js",
      "npm:bn.js@4.11.4.js",
      "npm:bn.js@4.11.4/lib/bn.js",
      "npm:create-hash@1.1.2.js",
      "npm:create-hash@1.1.2/browser.js",
      "npm:cipher-base@1.0.2.js",
      "npm:cipher-base@1.0.2/index.js",
      "github:jspm/nodelibs-string_decoder@0.1.0.js",
      "github:jspm/nodelibs-string_decoder@0.1.0/index.js",
      "npm:string_decoder@0.10.31.js",
      "npm:string_decoder@0.10.31/index.js",
      "npm:inherits@2.0.1.js",
      "npm:inherits@2.0.1/inherits_browser.js",
      "github:jspm/nodelibs-stream@0.1.0.js",
      "github:jspm/nodelibs-stream@0.1.0/index.js",
      "npm:stream-browserify@1.0.0.js",
      "npm:stream-browserify@1.0.0/index.js",
      "npm:readable-stream@1.1.14/passthrough.js",
      "npm:readable-stream@1.1.14/lib/_stream_passthrough.js",
      "npm:core-util-is@1.0.2.js",
      "npm:core-util-is@1.0.2/lib/util.js",
      "npm:readable-stream@1.1.14/lib/_stream_transform.js",
      "npm:readable-stream@1.1.14/lib/_stream_duplex.js",
      "npm:readable-stream@1.1.14/lib/_stream_writable.js",
      "npm:readable-stream@1.1.14/lib/_stream_readable.js",
      "github:jspm/nodelibs-events@0.1.1.js",
      "github:jspm/nodelibs-events@0.1.1/index.js",
      "npm:events@1.0.2.js",
      "npm:events@1.0.2/events.js",
      "npm:isarray@0.0.1.js",
      "npm:isarray@0.0.1/index.js",
      "npm:readable-stream@1.1.14/transform.js",
      "npm:readable-stream@1.1.14/duplex.js",
      "npm:readable-stream@1.1.14/writable.js",
      "npm:readable-stream@1.1.14/readable.js",
      "npm:sha.js@2.4.5.js",
      "npm:sha.js@2.4.5/index.js",
      "npm:sha.js@2.4.5/sha512.js",
      "npm:sha.js@2.4.5/hash.js",
      "npm:sha.js@2.4.5/sha384.js",
      "npm:sha.js@2.4.5/sha256.js",
      "npm:sha.js@2.4.5/sha224.js",
      "npm:sha.js@2.4.5/sha1.js",
      "npm:sha.js@2.4.5/sha.js",
      "npm:ripemd160@1.0.1.js",
      "npm:ripemd160@1.0.1/lib/ripemd160.js",
      "npm:create-hash@1.1.2/md5.js",
      "npm:create-hash@1.1.2/helpers.js",
      "npm:browserify-rsa@4.0.1.js",
      "npm:browserify-rsa@4.0.1/index.js",
      "npm:randombytes@2.0.3.js",
      "npm:randombytes@2.0.3/browser.js",
      "npm:public-encrypt@4.0.0/xor.js",
      "npm:public-encrypt@4.0.0/mgf.js",
      "npm:parse-asn1@5.0.0.js",
      "npm:parse-asn1@5.0.0/index.js",
      "npm:pbkdf2@3.0.4.js",
      "npm:pbkdf2@3.0.4/browser.js",
      "npm:create-hmac@1.1.4.js",
      "npm:create-hmac@1.1.4/browser.js",
      "npm:browserify-aes@1.0.6.js",
      "npm:browserify-aes@1.0.6/browser.js",
      "npm:browserify-aes@1.0.6/modes.js",
      "npm:browserify-aes@1.0.6/decrypter.js",
      "npm:browserify-aes@1.0.6/modes/ctr.js",
      "npm:buffer-xor@1.0.3.js",
      "npm:buffer-xor@1.0.3/index.js",
      "npm:browserify-aes@1.0.6/modes/ofb.js",
      "npm:browserify-aes@1.0.6/modes/cfb1.js",
      "npm:browserify-aes@1.0.6/modes/cfb8.js",
      "npm:browserify-aes@1.0.6/modes/cfb.js",
      "npm:browserify-aes@1.0.6/modes/cbc.js",
      "npm:browserify-aes@1.0.6/modes/ecb.js",
      "npm:evp_bytestokey@1.0.0.js",
      "npm:evp_bytestokey@1.0.0/index.js",
      "npm:browserify-aes@1.0.6/authCipher.js",
      "npm:browserify-aes@1.0.6/ghash.js",
      "npm:browserify-aes@1.0.6/aes.js",
      "npm:browserify-aes@1.0.6/streamCipher.js",
      "npm:browserify-aes@1.0.6/encrypter.js",
      "npm:parse-asn1@5.0.0/fixProc.js",
      "npm:parse-asn1@5.0.0/aesid.json!github:systemjs/plugin-json@0.1.2.js",
      "npm:parse-asn1@5.0.0/asn1.js",
      "npm:asn1.js@4.6.2.js",
      "npm:asn1.js@4.6.2/lib/asn1.js",
      "npm:asn1.js@4.6.2/lib/asn1/encoders/index.js",
      "npm:asn1.js@4.6.2/lib/asn1/encoders/pem.js",
      "npm:asn1.js@4.6.2/lib/asn1/encoders/der.js",
      "npm:asn1.js@4.6.2/lib/asn1/decoders/index.js",
      "npm:asn1.js@4.6.2/lib/asn1/decoders/pem.js",
      "npm:asn1.js@4.6.2/lib/asn1/decoders/der.js",
      "npm:asn1.js@4.6.2/lib/asn1/constants/index.js",
      "npm:asn1.js@4.6.2/lib/asn1/constants/der.js",
      "npm:asn1.js@4.6.2/lib/asn1/base/index.js",
      "npm:asn1.js@4.6.2/lib/asn1/base/node.js",
      "npm:minimalistic-assert@1.0.0.js",
      "npm:minimalistic-assert@1.0.0/index.js",
      "npm:asn1.js@4.6.2/lib/asn1/base/buffer.js",
      "npm:asn1.js@4.6.2/lib/asn1/base/reporter.js",
      "npm:asn1.js@4.6.2/lib/asn1/api.js",
      "github:jspm/nodelibs-vm@0.1.0.js",
      "github:jspm/nodelibs-vm@0.1.0/index.js",
      "npm:vm-browserify@0.0.4.js",
      "npm:vm-browserify@0.0.4/index.js",
      "npm:indexof@0.0.1.js",
      "npm:indexof@0.0.1/index.js",
      "npm:public-encrypt@4.0.0/publicEncrypt.js",
      "npm:create-ecdh@4.0.0.js",
      "npm:create-ecdh@4.0.0/browser.js",
      "npm:elliptic@6.3.1.js",
      "npm:elliptic@6.3.1/lib/elliptic.js",
      "npm:elliptic@6.3.1/lib/elliptic/eddsa/index.js",
      "npm:elliptic@6.3.1/lib/elliptic/eddsa/signature.js",
      "npm:elliptic@6.3.1/lib/elliptic/eddsa/key.js",
      "npm:hash.js@1.0.3.js",
      "npm:hash.js@1.0.3/lib/hash.js",
      "npm:hash.js@1.0.3/lib/hash/hmac.js",
      "npm:hash.js@1.0.3/lib/hash/ripemd.js",
      "npm:hash.js@1.0.3/lib/hash/sha.js",
      "npm:hash.js@1.0.3/lib/hash/common.js",
      "npm:hash.js@1.0.3/lib/hash/utils.js",
      "npm:elliptic@6.3.1/lib/elliptic/ec/index.js",
      "npm:elliptic@6.3.1/lib/elliptic/ec/signature.js",
      "npm:elliptic@6.3.1/lib/elliptic/ec/key.js",
      "npm:elliptic@6.3.1/lib/elliptic/curves.js",
      "npm:elliptic@6.3.1/lib/elliptic/precomputed/secp256k1.js",
      "npm:elliptic@6.3.1/lib/elliptic/curve/index.js",
      "npm:elliptic@6.3.1/lib/elliptic/curve/edwards.js",
      "npm:elliptic@6.3.1/lib/elliptic/curve/mont.js",
      "npm:elliptic@6.3.1/lib/elliptic/curve/short.js",
      "npm:elliptic@6.3.1/lib/elliptic/curve/base.js",
      "npm:elliptic@6.3.1/lib/elliptic/hmac-drbg.js",
      "npm:brorand@1.0.5.js",
      "npm:brorand@1.0.5/index.js",
      "npm:elliptic@6.3.1/lib/elliptic/utils.js",
      "npm:elliptic@6.3.1/package.json!github:systemjs/plugin-json@0.1.2.js",
      "npm:browserify-sign@4.0.0.js",
      "npm:browserify-sign@4.0.0/browser.js",
      "npm:browserify-sign@4.0.0/verify.js",
      "npm:browserify-sign@4.0.0/curves.js",
      "npm:browserify-sign@4.0.0/sign.js",
      "npm:browserify-sign@4.0.0/algos.js",
      "npm:diffie-hellman@5.0.2.js",
      "npm:diffie-hellman@5.0.2/browser.js",
      "npm:diffie-hellman@5.0.2/lib/dh.js",
      "npm:diffie-hellman@5.0.2/lib/generatePrime.js",
      "npm:miller-rabin@4.0.0.js",
      "npm:miller-rabin@4.0.0/lib/mr.js",
      "npm:diffie-hellman@5.0.2/lib/primes.json!github:systemjs/plugin-json@0.1.2.js",
      "npm:browserify-cipher@1.0.0.js",
      "npm:browserify-cipher@1.0.0/browser.js",
      "npm:browserify-des@1.0.0/modes.js",
      "npm:browserify-des@1.0.0.js",
      "npm:browserify-des@1.0.0/index.js",
      "npm:des.js@1.0.0.js",
      "npm:des.js@1.0.0/lib/des.js",
      "npm:des.js@1.0.0/lib/des/ede.js",
      "npm:des.js@1.0.0/lib/des/cbc.js",
      "npm:des.js@1.0.0/lib/des/des.js",
      "npm:des.js@1.0.0/lib/des/cipher.js",
      "npm:des.js@1.0.0/lib/des/utils.js",
      "npm:core-js@2.4.0.js",
      "npm:core-js@2.4.0/index.js",
      "npm:core-js@2.4.0/modules/_core.js",
      "npm:core-js@2.4.0/modules/core.string.unescape-html.js",
      "npm:core-js@2.4.0/modules/_replacer.js",
      "npm:core-js@2.4.0/modules/_export.js",
      "npm:core-js@2.4.0/modules/_ctx.js",
      "npm:core-js@2.4.0/modules/_a-function.js",
      "npm:core-js@2.4.0/modules/_redefine.js",
      "npm:core-js@2.4.0/modules/_uid.js",
      "npm:core-js@2.4.0/modules/_has.js",
      "npm:core-js@2.4.0/modules/_hide.js",
      "npm:core-js@2.4.0/modules/_descriptors.js",
      "npm:core-js@2.4.0/modules/_fails.js",
      "npm:core-js@2.4.0/modules/_property-desc.js",
      "npm:core-js@2.4.0/modules/_object-dp.js",
      "npm:core-js@2.4.0/modules/_to-primitive.js",
      "npm:core-js@2.4.0/modules/_is-object.js",
      "npm:core-js@2.4.0/modules/_ie8-dom-define.js",
      "npm:core-js@2.4.0/modules/_dom-create.js",
      "npm:core-js@2.4.0/modules/_global.js",
      "npm:core-js@2.4.0/modules/_an-object.js",
      "npm:core-js@2.4.0/modules/core.string.escape-html.js",
      "npm:core-js@2.4.0/modules/core.regexp.escape.js",
      "npm:core-js@2.4.0/modules/core.number.iterator.js",
      "npm:core-js@2.4.0/modules/_iter-define.js",
      "npm:core-js@2.4.0/modules/_wks.js",
      "npm:core-js@2.4.0/modules/_shared.js",
      "npm:core-js@2.4.0/modules/_object-gpo.js",
      "npm:core-js@2.4.0/modules/_shared-key.js",
      "npm:core-js@2.4.0/modules/_to-object.js",
      "npm:core-js@2.4.0/modules/_defined.js",
      "npm:core-js@2.4.0/modules/_set-to-string-tag.js",
      "npm:core-js@2.4.0/modules/_iter-create.js",
      "npm:core-js@2.4.0/modules/_object-create.js",
      "npm:core-js@2.4.0/modules/_html.js",
      "npm:core-js@2.4.0/modules/_enum-bug-keys.js",
      "npm:core-js@2.4.0/modules/_object-dps.js",
      "npm:core-js@2.4.0/modules/_object-keys.js",
      "npm:core-js@2.4.0/modules/_object-keys-internal.js",
      "npm:core-js@2.4.0/modules/_array-includes.js",
      "npm:core-js@2.4.0/modules/_to-index.js",
      "npm:core-js@2.4.0/modules/_to-integer.js",
      "npm:core-js@2.4.0/modules/_to-length.js",
      "npm:core-js@2.4.0/modules/_to-iobject.js",
      "npm:core-js@2.4.0/modules/_iobject.js",
      "npm:core-js@2.4.0/modules/_cof.js",
      "npm:core-js@2.4.0/modules/_iterators.js",
      "npm:core-js@2.4.0/modules/_library.js",
      "npm:core-js@2.4.0/modules/core.object.make.js",
      "npm:core-js@2.4.0/modules/_object-define.js",
      "npm:core-js@2.4.0/modules/_own-keys.js",
      "npm:core-js@2.4.0/modules/_object-gops.js",
      "npm:core-js@2.4.0/modules/_object-gopn.js",
      "npm:core-js@2.4.0/modules/_object-gopd.js",
      "npm:core-js@2.4.0/modules/_object-pie.js",
      "npm:core-js@2.4.0/modules/core.object.define.js",
      "npm:core-js@2.4.0/modules/core.object.classof.js",
      "npm:core-js@2.4.0/modules/_classof.js",
      "npm:core-js@2.4.0/modules/core.object.is-object.js",
      "npm:core-js@2.4.0/modules/core.function.part.js",
      "npm:core-js@2.4.0/modules/_partial.js",
      "npm:core-js@2.4.0/modules/_invoke.js",
      "npm:core-js@2.4.0/modules/_path.js",
      "npm:core-js@2.4.0/modules/core.delay.js",
      "npm:core-js@2.4.0/modules/core.is-iterable.js",
      "npm:core-js@2.4.0/modules/core.get-iterator.js",
      "npm:core-js@2.4.0/modules/core.get-iterator-method.js",
      "npm:core-js@2.4.0/modules/core.dict.js",
      "npm:core-js@2.4.0/modules/_iter-step.js",
      "npm:core-js@2.4.0/modules/_for-of.js",
      "npm:core-js@2.4.0/modules/_is-array-iter.js",
      "npm:core-js@2.4.0/modules/_iter-call.js",
      "npm:core-js@2.4.0/modules/_keyof.js",
      "npm:core-js@2.4.0/modules/_object-assign.js",
      "npm:core-js@2.4.0/shim.js",
      "npm:core-js@2.4.0/modules/web.dom.iterable.js",
      "npm:core-js@2.4.0/modules/es6.array.iterator.js",
      "npm:core-js@2.4.0/modules/_add-to-unscopables.js",
      "npm:core-js@2.4.0/modules/web.immediate.js",
      "npm:core-js@2.4.0/modules/_task.js",
      "npm:core-js@2.4.0/modules/web.timers.js",
      "npm:core-js@2.4.0/modules/es7.observable.js",
      "npm:core-js@2.4.0/modules/_set-species.js",
      "npm:core-js@2.4.0/modules/_redefine-all.js",
      "npm:core-js@2.4.0/modules/_an-instance.js",
      "npm:core-js@2.4.0/modules/_microtask.js",
      "npm:core-js@2.4.0/modules/es7.asap.js",
      "npm:core-js@2.4.0/modules/es7.reflect.metadata.js",
      "npm:core-js@2.4.0/modules/_metadata.js",
      "npm:core-js@2.4.0/modules/es6.weak-map.js",
      "npm:core-js@2.4.0/modules/_collection.js",
      "npm:core-js@2.4.0/modules/_inherit-if-required.js",
      "npm:core-js@2.4.0/modules/_set-proto.js",
      "npm:core-js@2.4.0/modules/_iter-detect.js",
      "npm:core-js@2.4.0/modules/_meta.js",
      "npm:core-js@2.4.0/modules/_collection-weak.js",
      "npm:core-js@2.4.0/modules/_array-methods.js",
      "npm:core-js@2.4.0/modules/_array-species-create.js",
      "npm:core-js@2.4.0/modules/_array-species-constructor.js",
      "npm:core-js@2.4.0/modules/_is-array.js",
      "npm:core-js@2.4.0/modules/es6.map.js",
      "npm:core-js@2.4.0/modules/_collection-strong.js",
      "npm:core-js@2.4.0/modules/es7.reflect.has-own-metadata.js",
      "npm:core-js@2.4.0/modules/es7.reflect.has-metadata.js",
      "npm:core-js@2.4.0/modules/es7.reflect.get-own-metadata-keys.js",
      "npm:core-js@2.4.0/modules/es7.reflect.get-own-metadata.js",
      "npm:core-js@2.4.0/modules/es7.reflect.get-metadata-keys.js",
      "npm:core-js@2.4.0/modules/_array-from-iterable.js",
      "npm:core-js@2.4.0/modules/es6.set.js",
      "npm:core-js@2.4.0/modules/es7.reflect.get-metadata.js",
      "npm:core-js@2.4.0/modules/es7.reflect.delete-metadata.js",
      "npm:core-js@2.4.0/modules/es7.reflect.define-metadata.js",
      "npm:core-js@2.4.0/modules/es7.math.umulh.js",
      "npm:core-js@2.4.0/modules/es7.math.imulh.js",
      "npm:core-js@2.4.0/modules/es7.math.isubh.js",
      "npm:core-js@2.4.0/modules/es7.math.iaddh.js",
      "npm:core-js@2.4.0/modules/es7.error.is-error.js",
      "npm:core-js@2.4.0/modules/es7.system.global.js",
      "npm:core-js@2.4.0/modules/es7.set.to-json.js",
      "npm:core-js@2.4.0/modules/_collection-to-json.js",
      "npm:core-js@2.4.0/modules/es7.map.to-json.js",
      "npm:core-js@2.4.0/modules/es7.object.lookup-setter.js",
      "npm:core-js@2.4.0/modules/_object-forced-pam.js",
      "npm:core-js@2.4.0/modules/es7.object.lookup-getter.js",
      "npm:core-js@2.4.0/modules/es7.object.define-setter.js",
      "npm:core-js@2.4.0/modules/es7.object.define-getter.js",
      "npm:core-js@2.4.0/modules/es7.object.entries.js",
      "npm:core-js@2.4.0/modules/_object-to-array.js",
      "npm:core-js@2.4.0/modules/es7.object.values.js",
      "npm:core-js@2.4.0/modules/es7.object.get-own-property-descriptors.js",
      "npm:core-js@2.4.0/modules/_create-property.js",
      "npm:core-js@2.4.0/modules/es7.symbol.observable.js",
      "npm:core-js@2.4.0/modules/_wks-define.js",
      "npm:core-js@2.4.0/modules/_wks-ext.js",
      "npm:core-js@2.4.0/modules/es7.symbol.async-iterator.js",
      "npm:core-js@2.4.0/modules/es7.string.match-all.js",
      "npm:core-js@2.4.0/modules/_flags.js",
      "npm:core-js@2.4.0/modules/_is-regexp.js",
      "npm:core-js@2.4.0/modules/es7.string.trim-right.js",
      "npm:core-js@2.4.0/modules/_string-trim.js",
      "npm:core-js@2.4.0/modules/_string-ws.js",
      "npm:core-js@2.4.0/modules/es7.string.trim-left.js",
      "npm:core-js@2.4.0/modules/es7.string.pad-end.js",
      "npm:core-js@2.4.0/modules/_string-pad.js",
      "npm:core-js@2.4.0/modules/_string-repeat.js",
      "npm:core-js@2.4.0/modules/es7.string.pad-start.js",
      "npm:core-js@2.4.0/modules/es7.string.at.js",
      "npm:core-js@2.4.0/modules/_string-at.js",
      "npm:core-js@2.4.0/modules/es7.array.includes.js",
      "npm:core-js@2.4.0/modules/es6.reflect.set-prototype-of.js",
      "npm:core-js@2.4.0/modules/es6.reflect.set.js",
      "npm:core-js@2.4.0/modules/es6.reflect.prevent-extensions.js",
      "npm:core-js@2.4.0/modules/es6.reflect.own-keys.js",
      "npm:core-js@2.4.0/modules/es6.reflect.is-extensible.js",
      "npm:core-js@2.4.0/modules/es6.reflect.has.js",
      "npm:core-js@2.4.0/modules/es6.reflect.get-prototype-of.js",
      "npm:core-js@2.4.0/modules/es6.reflect.get-own-property-descriptor.js",
      "npm:core-js@2.4.0/modules/es6.reflect.get.js",
      "npm:core-js@2.4.0/modules/es6.reflect.enumerate.js",
      "npm:core-js@2.4.0/modules/es6.reflect.delete-property.js",
      "npm:core-js@2.4.0/modules/es6.reflect.define-property.js",
      "npm:core-js@2.4.0/modules/es6.reflect.construct.js",
      "npm:core-js@2.4.0/modules/_bind.js",
      "npm:core-js@2.4.0/modules/es6.reflect.apply.js",
      "npm:core-js@2.4.0/modules/es6.typed.float64-array.js",
      "npm:core-js@2.4.0/modules/_typed-array.js",
      "npm:core-js@2.4.0/modules/_array-copy-within.js",
      "npm:core-js@2.4.0/modules/_array-fill.js",
      "npm:core-js@2.4.0/modules/_species-constructor.js",
      "npm:core-js@2.4.0/modules/_same-value.js",
      "npm:core-js@2.4.0/modules/_is-integer.js",
      "npm:core-js@2.4.0/modules/_typed-buffer.js",
      "npm:core-js@2.4.0/modules/_typed.js",
      "npm:core-js@2.4.0/modules/es6.typed.float32-array.js",
      "npm:core-js@2.4.0/modules/es6.typed.uint32-array.js",
      "npm:core-js@2.4.0/modules/es6.typed.int32-array.js",
      "npm:core-js@2.4.0/modules/es6.typed.uint16-array.js",
      "npm:core-js@2.4.0/modules/es6.typed.int16-array.js",
      "npm:core-js@2.4.0/modules/es6.typed.uint8-clamped-array.js",
      "npm:core-js@2.4.0/modules/es6.typed.uint8-array.js",
      "npm:core-js@2.4.0/modules/es6.typed.int8-array.js",
      "npm:core-js@2.4.0/modules/es6.typed.data-view.js",
      "npm:core-js@2.4.0/modules/es6.typed.array-buffer.js",
      "npm:core-js@2.4.0/modules/es6.weak-set.js",
      "npm:core-js@2.4.0/modules/es6.promise.js",
      "npm:core-js@2.4.0/modules/es6.regexp.split.js",
      "npm:core-js@2.4.0/modules/_fix-re-wks.js",
      "npm:core-js@2.4.0/modules/es6.regexp.search.js",
      "npm:core-js@2.4.0/modules/es6.regexp.replace.js",
      "npm:core-js@2.4.0/modules/es6.regexp.match.js",
      "npm:core-js@2.4.0/modules/es6.regexp.flags.js",
      "npm:core-js@2.4.0/modules/es6.regexp.to-string.js",
      "npm:core-js@2.4.0/modules/es6.regexp.constructor.js",
      "npm:core-js@2.4.0/modules/es6.array.species.js",
      "npm:core-js@2.4.0/modules/es6.array.find-index.js",
      "npm:core-js@2.4.0/modules/es6.array.find.js",
      "npm:core-js@2.4.0/modules/es6.array.fill.js",
      "npm:core-js@2.4.0/modules/es6.array.copy-within.js",
      "npm:core-js@2.4.0/modules/es6.array.last-index-of.js",
      "npm:core-js@2.4.0/modules/_strict-method.js",
      "npm:core-js@2.4.0/modules/es6.array.index-of.js",
      "npm:core-js@2.4.0/modules/es6.array.reduce-right.js",
      "npm:core-js@2.4.0/modules/_array-reduce.js",
      "npm:core-js@2.4.0/modules/es6.array.reduce.js",
      "npm:core-js@2.4.0/modules/es6.array.every.js",
      "npm:core-js@2.4.0/modules/es6.array.some.js",
      "npm:core-js@2.4.0/modules/es6.array.filter.js",
      "npm:core-js@2.4.0/modules/es6.array.map.js",
      "npm:core-js@2.4.0/modules/es6.array.for-each.js",
      "npm:core-js@2.4.0/modules/es6.array.sort.js",
      "npm:core-js@2.4.0/modules/es6.array.slice.js",
      "npm:core-js@2.4.0/modules/es6.array.join.js",
      "npm:core-js@2.4.0/modules/es6.array.of.js",
      "npm:core-js@2.4.0/modules/es6.array.from.js",
      "npm:core-js@2.4.0/modules/es6.array.is-array.js",
      "npm:core-js@2.4.0/modules/es6.date.to-primitive.js",
      "npm:core-js@2.4.0/modules/_date-to-primitive.js",
      "npm:core-js@2.4.0/modules/es6.date.to-string.js",
      "npm:core-js@2.4.0/modules/es6.date.to-iso-string.js",
      "npm:core-js@2.4.0/modules/es6.date.to-json.js",
      "npm:core-js@2.4.0/modules/es6.date.now.js",
      "npm:core-js@2.4.0/modules/es6.string.sup.js",
      "npm:core-js@2.4.0/modules/_string-html.js",
      "npm:core-js@2.4.0/modules/es6.string.sub.js",
      "npm:core-js@2.4.0/modules/es6.string.strike.js",
      "npm:core-js@2.4.0/modules/es6.string.small.js",
      "npm:core-js@2.4.0/modules/es6.string.link.js",
      "npm:core-js@2.4.0/modules/es6.string.italics.js",
      "npm:core-js@2.4.0/modules/es6.string.fontsize.js",
      "npm:core-js@2.4.0/modules/es6.string.fontcolor.js",
      "npm:core-js@2.4.0/modules/es6.string.fixed.js",
      "npm:core-js@2.4.0/modules/es6.string.bold.js",
      "npm:core-js@2.4.0/modules/es6.string.blink.js",
      "npm:core-js@2.4.0/modules/es6.string.big.js",
      "npm:core-js@2.4.0/modules/es6.string.anchor.js",
      "npm:core-js@2.4.0/modules/es6.string.starts-with.js",
      "npm:core-js@2.4.0/modules/_fails-is-regexp.js",
      "npm:core-js@2.4.0/modules/_string-context.js",
      "npm:core-js@2.4.0/modules/es6.string.repeat.js",
      "npm:core-js@2.4.0/modules/es6.string.includes.js",
      "npm:core-js@2.4.0/modules/es6.string.ends-with.js",
      "npm:core-js@2.4.0/modules/es6.string.code-point-at.js",
      "npm:core-js@2.4.0/modules/es6.string.iterator.js",
      "npm:core-js@2.4.0/modules/es6.string.trim.js",
      "npm:core-js@2.4.0/modules/es6.string.raw.js",
      "npm:core-js@2.4.0/modules/es6.string.from-code-point.js",
      "npm:core-js@2.4.0/modules/es6.math.trunc.js",
      "npm:core-js@2.4.0/modules/es6.math.tanh.js",
      "npm:core-js@2.4.0/modules/_math-expm1.js",
      "npm:core-js@2.4.0/modules/es6.math.sinh.js",
      "npm:core-js@2.4.0/modules/es6.math.sign.js",
      "npm:core-js@2.4.0/modules/_math-sign.js",
      "npm:core-js@2.4.0/modules/es6.math.log2.js",
      "npm:core-js@2.4.0/modules/es6.math.log1p.js",
      "npm:core-js@2.4.0/modules/_math-log1p.js",
      "npm:core-js@2.4.0/modules/es6.math.log10.js",
      "npm:core-js@2.4.0/modules/es6.math.imul.js",
      "npm:core-js@2.4.0/modules/es6.math.hypot.js",
      "npm:core-js@2.4.0/modules/es6.math.fround.js",
      "npm:core-js@2.4.0/modules/es6.math.expm1.js",
      "npm:core-js@2.4.0/modules/es6.math.cosh.js",
      "npm:core-js@2.4.0/modules/es6.math.clz32.js",
      "npm:core-js@2.4.0/modules/es6.math.cbrt.js",
      "npm:core-js@2.4.0/modules/es6.math.atanh.js",
      "npm:core-js@2.4.0/modules/es6.math.asinh.js",
      "npm:core-js@2.4.0/modules/es6.math.acosh.js",
      "npm:core-js@2.4.0/modules/es6.number.parse-int.js",
      "npm:core-js@2.4.0/modules/_parse-int.js",
      "npm:core-js@2.4.0/modules/es6.number.parse-float.js",
      "npm:core-js@2.4.0/modules/_parse-float.js",
      "npm:core-js@2.4.0/modules/es6.number.min-safe-integer.js",
      "npm:core-js@2.4.0/modules/es6.number.max-safe-integer.js",
      "npm:core-js@2.4.0/modules/es6.number.is-safe-integer.js",
      "npm:core-js@2.4.0/modules/es6.number.is-nan.js",
      "npm:core-js@2.4.0/modules/es6.number.is-integer.js",
      "npm:core-js@2.4.0/modules/es6.number.is-finite.js",
      "npm:core-js@2.4.0/modules/es6.number.epsilon.js",
      "npm:core-js@2.4.0/modules/es6.number.to-precision.js",
      "npm:core-js@2.4.0/modules/_a-number-value.js",
      "npm:core-js@2.4.0/modules/es6.number.to-fixed.js",
      "npm:core-js@2.4.0/modules/es6.number.constructor.js",
      "npm:core-js@2.4.0/modules/es6.parse-float.js",
      "npm:core-js@2.4.0/modules/es6.parse-int.js",
      "npm:core-js@2.4.0/modules/es6.function.has-instance.js",
      "npm:core-js@2.4.0/modules/es6.function.name.js",
      "npm:core-js@2.4.0/modules/es6.function.bind.js",
      "npm:core-js@2.4.0/modules/es6.object.to-string.js",
      "npm:core-js@2.4.0/modules/es6.object.set-prototype-of.js",
      "npm:core-js@2.4.0/modules/es6.object.is.js",
      "npm:core-js@2.4.0/modules/es6.object.assign.js",
      "npm:core-js@2.4.0/modules/es6.object.is-extensible.js",
      "npm:core-js@2.4.0/modules/_object-sap.js",
      "npm:core-js@2.4.0/modules/es6.object.is-sealed.js",
      "npm:core-js@2.4.0/modules/es6.object.is-frozen.js",
      "npm:core-js@2.4.0/modules/es6.object.prevent-extensions.js",
      "npm:core-js@2.4.0/modules/es6.object.seal.js",
      "npm:core-js@2.4.0/modules/es6.object.freeze.js",
      "npm:core-js@2.4.0/modules/es6.object.get-own-property-names.js",
      "npm:core-js@2.4.0/modules/_object-gopn-ext.js",
      "npm:core-js@2.4.0/modules/es6.object.keys.js",
      "npm:core-js@2.4.0/modules/es6.object.get-prototype-of.js",
      "npm:core-js@2.4.0/modules/es6.object.get-own-property-descriptor.js",
      "npm:core-js@2.4.0/modules/es6.object.define-properties.js",
      "npm:core-js@2.4.0/modules/es6.object.define-property.js",
      "npm:core-js@2.4.0/modules/es6.object.create.js",
      "npm:core-js@2.4.0/modules/es6.symbol.js",
      "npm:core-js@2.4.0/modules/_enum-keys.js",
      "npm:@angular/router@3.0.0-beta.2.js",
      "npm:@angular/router@3.0.0-beta.2/index.js",
      "npm:@angular/router@3.0.0-beta.2/src/url_tree.js",
      "npm:@angular/router@3.0.0-beta.2/src/utils/collection.js",
      "npm:@angular/router@3.0.0-beta.2/src/shared.js",
      "npm:@angular/router@3.0.0-beta.2/src/router_state.js",
      "npm:@angular/router@3.0.0-beta.2/src/utils/tree.js",
      "npm:rxjs@5.0.0-beta.6/BehaviorSubject.js",
      "npm:rxjs@5.0.0-beta.6/util/ObjectUnsubscribedError.js",
      "npm:rxjs@5.0.0-beta.6/util/throwError.js",
      "npm:rxjs@5.0.0-beta.6/Subject.js",
      "npm:rxjs@5.0.0-beta.6/symbol/rxSubscriber.js",
      "npm:rxjs@5.0.0-beta.6/util/root.js",
      "npm:rxjs@5.0.0-beta.6/SubjectSubscription.js",
      "npm:rxjs@5.0.0-beta.6/Subscription.js",
      "npm:rxjs@5.0.0-beta.6/util/UnsubscriptionError.js",
      "npm:rxjs@5.0.0-beta.6/util/errorObject.js",
      "npm:rxjs@5.0.0-beta.6/util/tryCatch.js",
      "npm:rxjs@5.0.0-beta.6/util/isFunction.js",
      "npm:rxjs@5.0.0-beta.6/util/isObject.js",
      "npm:rxjs@5.0.0-beta.6/util/isArray.js",
      "npm:rxjs@5.0.0-beta.6/Subscriber.js",
      "npm:rxjs@5.0.0-beta.6/Observer.js",
      "npm:rxjs@5.0.0-beta.6/Observable.js",
      "npm:rxjs@5.0.0-beta.6/util/toSubscriber.js",
      "npm:rxjs@5.0.0-beta.6/symbol/observable.js",
      "npm:@angular/router@3.0.0-beta.2/src/router_providers.js",
      "npm:@angular/router@3.0.0-beta.2/src/common_router_providers.js",
      "npm:@angular/router@3.0.0-beta.2/src/router_outlet_map.js",
      "npm:@angular/router@3.0.0-beta.2/src/router.js",
      "npm:@angular/router@3.0.0-beta.2/src/resolve.js",
      "npm:rxjs@5.0.0-beta.6/observable/fromPromise.js",
      "npm:rxjs@5.0.0-beta.6/observable/PromiseObservable.js",
      "npm:rxjs@5.0.0-beta.6/observable/forkJoin.js",
      "npm:rxjs@5.0.0-beta.6/observable/ForkJoinObservable.js",
      "npm:rxjs@5.0.0-beta.6/OuterSubscriber.js",
      "npm:rxjs@5.0.0-beta.6/util/subscribeToResult.js",
      "npm:rxjs@5.0.0-beta.6/InnerSubscriber.js",
      "npm:rxjs@5.0.0-beta.6/symbol/iterator.js",
      "npm:rxjs@5.0.0-beta.6/util/isPromise.js",
      "npm:rxjs@5.0.0-beta.6/observable/EmptyObservable.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/toPromise.js",
      "npm:rxjs@5.0.0-beta.6/operator/toPromise.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/map.js",
      "npm:rxjs@5.0.0-beta.6/operator/map.js",
      "npm:@angular/router@3.0.0-beta.2/src/recognize.js",
      "npm:rxjs@5.0.0-beta.6/observable/of.js",
      "npm:rxjs@5.0.0-beta.6/observable/ArrayObservable.js",
      "npm:rxjs@5.0.0-beta.6/util/isScheduler.js",
      "npm:rxjs@5.0.0-beta.6/observable/ScalarObservable.js",
      "npm:@angular/router@3.0.0-beta.2/src/create_url_tree.js",
      "npm:@angular/router@3.0.0-beta.2/src/create_router_state.js",
      "npm:@angular/router@3.0.0-beta.2/src/config.js",
      "npm:@angular/router@3.0.0-beta.2/src/apply_redirects.js",
      "npm:@angular/core@2.0.0-rc.4.js",
      "npm:@angular/core@2.0.0-rc.4/index.js",
      "npm:@angular/core@2.0.0-rc.4/src/animation/animation_player.js",
      "npm:@angular/core@2.0.0-rc.4/src/facade/lang.js",
      "npm:@angular/core@2.0.0-rc.4/src/facade/exceptions.js",
      "npm:@angular/core@2.0.0-rc.4/src/facade/exception_handler.js",
      "npm:@angular/core@2.0.0-rc.4/src/facade/collection.js",
      "npm:@angular/core@2.0.0-rc.4/src/facade/base_wrapped_exception.js",
      "npm:@angular/core@2.0.0-rc.4/src/animation/metadata.js",
      "npm:@angular/core@2.0.0-rc.4/private_export.js",
      "npm:@angular/core@2.0.0-rc.4/src/util/decorators.js",
      "npm:@angular/core@2.0.0-rc.4/src/security.js",
      "npm:@angular/core@2.0.0-rc.4/src/render/api.js",
      "npm:@angular/core@2.0.0-rc.4/src/reflection/reflector_reader.js",
      "npm:@angular/core@2.0.0-rc.4/src/reflection/reflection_capabilities.js",
      "npm:@angular/core@2.0.0-rc.4/src/reflection/reflection.js",
      "npm:@angular/core@2.0.0-rc.4/src/reflection/reflector.js",
      "npm:@angular/core@2.0.0-rc.4/src/profile/wtf_init.js",
      "npm:@angular/core@2.0.0-rc.4/src/metadata/view.js",
      "npm:@angular/core@2.0.0-rc.4/src/metadata/lifecycle_hooks.js",
      "npm:@angular/core@2.0.0-rc.4/src/linker/view_utils.js",
      "npm:@angular/core@2.0.0-rc.4/src/linker/exceptions.js",
      "npm:@angular/core@2.0.0-rc.4/src/linker/element.js",
      "npm:@angular/core@2.0.0-rc.4/src/linker/view_type.js",
      "npm:@angular/core@2.0.0-rc.4/src/linker/view_container_ref.js",
      "npm:@angular/core@2.0.0-rc.4/src/profile/profile.js",
      "npm:@angular/core@2.0.0-rc.4/src/profile/wtf_impl.js",
      "npm:@angular/core@2.0.0-rc.4/src/linker/element_ref.js",
      "npm:@angular/core@2.0.0-rc.4/src/di/decorators.js",
      "npm:@angular/core@2.0.0-rc.4/src/di/metadata.js",
      "npm:@angular/core@2.0.0-rc.4/src/change_detection/change_detection_util.js",
      "npm:@angular/core@2.0.0-rc.4/src/change_detection/change_detection.js",
      "npm:@angular/core@2.0.0-rc.4/src/change_detection/constants.js",
      "npm:@angular/core@2.0.0-rc.4/src/change_detection/change_detector_ref.js",
      "npm:@angular/core@2.0.0-rc.4/src/change_detection/differs/keyvalue_differs.js",
      "npm:@angular/core@2.0.0-rc.4/src/di.js",
      "npm:@angular/core@2.0.0-rc.4/src/di/opaque_token.js",
      "npm:@angular/core@2.0.0-rc.4/src/di/reflective_exceptions.js",
      "npm:@angular/core@2.0.0-rc.4/src/di/reflective_key.js",
      "npm:@angular/core@2.0.0-rc.4/src/di/forward_ref.js",
      "npm:@angular/core@2.0.0-rc.4/src/di/reflective_provider.js",
      "npm:@angular/core@2.0.0-rc.4/src/di/provider_util.js",
      "npm:@angular/core@2.0.0-rc.4/src/di/provider.js",
      "npm:@angular/core@2.0.0-rc.4/src/di/reflective_injector.js",
      "npm:@angular/core@2.0.0-rc.4/src/di/injector.js",
      "npm:@angular/core@2.0.0-rc.4/src/change_detection/differs/iterable_differs.js",
      "npm:@angular/core@2.0.0-rc.4/src/change_detection/differs/default_keyvalue_differ.js",
      "npm:@angular/core@2.0.0-rc.4/src/change_detection/differs/default_iterable_differ.js",
      "npm:@angular/core@2.0.0-rc.4/src/application_tokens.js",
      "npm:@angular/core@2.0.0-rc.4/src/linker/view.js",
      "npm:@angular/core@2.0.0-rc.4/src/animation/active_animation_players_map.js",
      "npm:@angular/core@2.0.0-rc.4/src/animation/animation_group_player.js",
      "npm:@angular/core@2.0.0-rc.4/src/facade/math.js",
      "npm:@angular/core@2.0.0-rc.4/src/linker/element_injector.js",
      "npm:@angular/core@2.0.0-rc.4/src/linker/debug_context.js",
      "npm:@angular/core@2.0.0-rc.4/src/linker/view_ref.js",
      "npm:@angular/core@2.0.0-rc.4/src/facade/async.js",
      "npm:@angular/core@2.0.0-rc.4/src/facade/promise.js",
      "npm:@angular/core@2.0.0-rc.4/src/linker/template_ref.js",
      "npm:@angular/core@2.0.0-rc.4/src/linker/component_resolver.js",
      "npm:@angular/core@2.0.0-rc.4/src/linker/component_factory.js",
      "npm:@angular/core@2.0.0-rc.4/src/linker/component_factory_resolver.js",
      "npm:@angular/core@2.0.0-rc.4/src/debug/debug_renderer.js",
      "npm:@angular/core@2.0.0-rc.4/src/debug/debug_node.js",
      "npm:@angular/core@2.0.0-rc.4/src/console.js",
      "npm:@angular/core@2.0.0-rc.4/src/animation/animation_styles.js",
      "npm:@angular/core@2.0.0-rc.4/src/animation/animation_style_util.js",
      "npm:@angular/core@2.0.0-rc.4/src/animation/animation_constants.js",
      "npm:@angular/core@2.0.0-rc.4/src/animation/animation_sequence_player.js",
      "npm:@angular/core@2.0.0-rc.4/src/animation/animation_keyframe.js",
      "npm:@angular/core@2.0.0-rc.4/src/animation/animation_driver.js",
      "npm:@angular/core@2.0.0-rc.4/src/application_common_providers.js",
      "npm:@angular/core@2.0.0-rc.4/src/linker/dynamic_component_loader.js",
      "npm:@angular/core@2.0.0-rc.4/src/application_ref.js",
      "npm:@angular/core@2.0.0-rc.4/src/zone/ng_zone.js",
      "npm:@angular/core@2.0.0-rc.4/src/zone/ng_zone_impl.js",
      "npm:@angular/core@2.0.0-rc.4/src/testability/testability.js",
      "npm:@angular/core@2.0.0-rc.4/src/platform_common_providers.js",
      "npm:@angular/core@2.0.0-rc.4/src/platform_directives_and_pipes.js",
      "npm:@angular/core@2.0.0-rc.4/src/change_detection.js",
      "npm:@angular/core@2.0.0-rc.4/src/linker.js",
      "npm:@angular/core@2.0.0-rc.4/src/linker/systemjs_component_resolver.js",
      "npm:@angular/core@2.0.0-rc.4/src/linker/query_list.js",
      "npm:@angular/core@2.0.0-rc.4/src/linker/compiler.js",
      "npm:@angular/core@2.0.0-rc.4/src/render.js",
      "npm:@angular/core@2.0.0-rc.4/src/zone.js",
      "npm:@angular/core@2.0.0-rc.4/src/util.js",
      "npm:@angular/core@2.0.0-rc.4/src/metadata.js",
      "npm:@angular/core@2.0.0-rc.4/src/metadata/directives.js",
      "npm:@angular/core@2.0.0-rc.4/src/metadata/di.js",
      "npm:rxjs@5.0.0-beta.6/add/observable/forkJoin.js",
      "npm:rxjs@5.0.0-beta.6/add/observable/from.js",
      "npm:rxjs@5.0.0-beta.6/observable/from.js",
      "npm:rxjs@5.0.0-beta.6/observable/FromObservable.js",
      "npm:rxjs@5.0.0-beta.6/operator/observeOn.js",
      "npm:rxjs@5.0.0-beta.6/Notification.js",
      "npm:rxjs@5.0.0-beta.6/observable/ArrayLikeObservable.js",
      "npm:rxjs@5.0.0-beta.6/observable/IteratorObservable.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/every.js",
      "npm:rxjs@5.0.0-beta.6/operator/every.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/reduce.js",
      "npm:rxjs@5.0.0-beta.6/operator/reduce.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/mergeAll.js",
      "npm:rxjs@5.0.0-beta.6/operator/mergeAll.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/mergeMap.js",
      "npm:rxjs@5.0.0-beta.6/operator/mergeMap.js",
      "npm:@angular/common@2.0.0-rc.4.js",
      "npm:@angular/common@2.0.0-rc.4/index.js",
      "npm:@angular/common@2.0.0-rc.4/src/localization.js",
      "npm:@angular/common@2.0.0-rc.4/src/location.js",
      "npm:@angular/common@2.0.0-rc.4/src/location/location.js",
      "npm:@angular/common@2.0.0-rc.4/src/location/location_strategy.js",
      "npm:@angular/common@2.0.0-rc.4/src/facade/async.js",
      "npm:@angular/common@2.0.0-rc.4/src/facade/promise.js",
      "npm:@angular/common@2.0.0-rc.4/src/facade/lang.js",
      "npm:@angular/common@2.0.0-rc.4/src/location/path_location_strategy.js",
      "npm:@angular/common@2.0.0-rc.4/src/location/platform_location.js",
      "npm:@angular/common@2.0.0-rc.4/src/facade/exceptions.js",
      "npm:@angular/common@2.0.0-rc.4/src/facade/exception_handler.js",
      "npm:@angular/common@2.0.0-rc.4/src/facade/collection.js",
      "npm:@angular/common@2.0.0-rc.4/src/facade/base_wrapped_exception.js",
      "npm:@angular/common@2.0.0-rc.4/src/location/hash_location_strategy.js",
      "npm:@angular/common@2.0.0-rc.4/src/common_directives.js",
      "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated.js",
      "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/validators.js",
      "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/model.js",
      "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives/validators.js",
      "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives/select_control_value_accessor.js",
      "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives/control_value_accessor.js",
      "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives/ng_model.js",
      "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives/shared.js",
      "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives/select_multiple_control_value_accessor.js",
      "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives/radio_control_value_accessor.js",
      "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives/ng_control.js",
      "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives/abstract_control_directive.js",
      "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives/number_value_accessor.js",
      "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives/normalize_validator.js",
      "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives/default_value_accessor.js",
      "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives/checkbox_value_accessor.js",
      "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives/ng_form_model.js",
      "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives/control_container.js",
      "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives/ng_form_control.js",
      "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives/ng_form.js",
      "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives/ng_control_status.js",
      "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives/ng_control_name.js",
      "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives/ng_control_group.js",
      "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives.js",
      "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/form_builder.js",
      "npm:@angular/common@2.0.0-rc.4/src/directives.js",
      "npm:@angular/common@2.0.0-rc.4/src/directives/ng_template_outlet.js",
      "npm:@angular/common@2.0.0-rc.4/src/directives/ng_switch.js",
      "npm:@angular/common@2.0.0-rc.4/src/directives/ng_style.js",
      "npm:@angular/common@2.0.0-rc.4/src/directives/ng_plural.js",
      "npm:@angular/common@2.0.0-rc.4/src/directives/ng_if.js",
      "npm:@angular/common@2.0.0-rc.4/src/directives/ng_for.js",
      "npm:@angular/common@2.0.0-rc.4/src/directives/ng_class.js",
      "npm:@angular/common@2.0.0-rc.4/src/directives/core_directives.js",
      "npm:@angular/common@2.0.0-rc.4/src/pipes.js",
      "npm:@angular/common@2.0.0-rc.4/src/pipes/uppercase_pipe.js",
      "npm:@angular/common@2.0.0-rc.4/src/pipes/invalid_pipe_argument_exception.js",
      "npm:@angular/common@2.0.0-rc.4/src/pipes/slice_pipe.js",
      "npm:@angular/common@2.0.0-rc.4/src/pipes/replace_pipe.js",
      "npm:@angular/common@2.0.0-rc.4/src/pipes/number_pipe.js",
      "npm:@angular/common@2.0.0-rc.4/src/facade/intl.js",
      "npm:@angular/common@2.0.0-rc.4/src/pipes/lowercase_pipe.js",
      "npm:@angular/common@2.0.0-rc.4/src/pipes/json_pipe.js",
      "npm:@angular/common@2.0.0-rc.4/src/pipes/i18n_select_pipe.js",
      "npm:@angular/common@2.0.0-rc.4/src/pipes/i18n_plural_pipe.js",
      "npm:@angular/common@2.0.0-rc.4/src/pipes/date_pipe.js",
      "npm:@angular/common@2.0.0-rc.4/src/pipes/common_pipes.js",
      "npm:@angular/common@2.0.0-rc.4/src/pipes/async_pipe.js",
      "npm:@angular/platform-browser@2.0.0-rc.4.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/index.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/private_export.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/dom/shared_styles_host.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/dom/dom_tokens.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/dom/dom_adapter.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/facade/lang.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/facade/collection.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/dom/events/dom_events.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/dom/events/event_manager.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/facade/exceptions.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/facade/exception_handler.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/facade/base_wrapped_exception.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/dom/dom_renderer.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/dom/util.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/core_private.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/dom/debug/ng_probe.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/worker_app.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/web_workers/worker/worker_adapter.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/web_workers/worker/renderer.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/web_workers/worker/event_deserializer.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/web_workers/shared/serializer.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/web_workers/shared/serialized_types.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/web_workers/shared/render_store.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/web_workers/shared/messaging_api.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/web_workers/shared/message_bus.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/web_workers/shared/client_message_broker.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/facade/async.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/facade/promise.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/web_workers/shared/service_message_broker.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/web_workers/shared/post_message_bus.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/web_workers/shared/api.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/browser.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/security/dom_sanitization_service.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/security/url_sanitizer.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/security/style_sanitizer.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/security/html_sanitizer.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/dom/events/key_events.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/dom/events/hammer_gestures.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/dom/events/hammer_common.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/browser/testability.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/browser/location/browser_platform_location.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/browser/location/history.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/browser/browser_adapter.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/browser/generic_browser_adapter.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/dom/web_animations_driver.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/dom/web_animations_player.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/worker_render.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/web_workers/ui/renderer.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/web_workers/ui/event_dispatcher.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/web_workers/ui/event_serializer.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/web_workers/ui/location_providers.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/web_workers/ui/platform_location.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/web_workers/worker/location_providers.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/web_workers/worker/platform_location.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/dom/debug/by.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/browser/tools/tools.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/browser/tools/common_tools.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/facade/browser.js",
      "npm:@angular/platform-browser@2.0.0-rc.4/src/browser/title.js",
      "npm:@angular/router@3.0.0-beta.2/src/directives/router_outlet.js",
      "npm:@angular/router@3.0.0-beta.2/src/directives/router_link_active.js",
      "npm:@angular/router@3.0.0-beta.2/src/directives/router_link.js",
      "npm:@angular/platform-browser-dynamic@2.0.0-rc.4.js",
      "npm:@angular/platform-browser-dynamic@2.0.0-rc.4/index.js",
      "npm:@angular/platform-browser-dynamic@2.0.0-rc.4/src/xhr/xhr_impl.js",
      "npm:@angular/platform-browser-dynamic@2.0.0-rc.4/src/facade/promise.js",
      "npm:@angular/platform-browser-dynamic@2.0.0-rc.4/src/facade/lang.js",
      "npm:@angular/compiler@2.0.0-rc.4.js",
      "npm:@angular/compiler@2.0.0-rc.4/index.js",
      "npm:@angular/compiler@2.0.0-rc.4/compiler.js",
      "npm:@angular/compiler@2.0.0-rc.4/private_export.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/view_compiler/view_compiler.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/view_compiler/view_builder.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/view_compiler/util.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/identifiers.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/util.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/facade/lang.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/facade/collection.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/compile_metadata.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/url_resolver.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/selector.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/facade/exceptions.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/facade/exception_handler.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/facade/base_wrapped_exception.js",
      "npm:@angular/compiler@2.0.0-rc.4/core_private.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/output/output_ast.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/view_compiler/constants.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/view_compiler/compile_view.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/view_compiler/compile_query.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/view_compiler/compile_pipe.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/view_compiler/compile_method.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/view_compiler/compile_element.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/template_ast.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/animation/animation_compiler.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/animation/animation_parser.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/animation/styles_collection.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/animation/animation_ast.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/parse_util.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/facade/math.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/view_compiler/view_binder.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/view_compiler/lifecycle_binder.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/view_compiler/event_binder.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/view_compiler/expression_converter.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/view_compiler/compile_binding.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/view_compiler/property_binder.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/config.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/template_parser.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/provider_parser.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/html_ast.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/style_url_resolver.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/template_preparser.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/html_tags.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/schema/element_schema_registry.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/html_parser.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/html_lexer.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/interpolation_config.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/chars.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/expression_parser/parser.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/expression_parser/lexer.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/expression_parser/ast.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/style_compiler.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/shadow_css.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/schema/dom_element_schema_registry.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/schema/dom_security_schema.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/output/ts_emitter.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/output/abstract_emitter.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/output/path_util.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/metadata_resolver.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/view_resolver.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/pipe_resolver.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/directive_resolver.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/directive_lifecycle_reflector.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/assertions.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/i18n/xmb_serializer.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/i18n/message.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/i18n/message_extractor.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/i18n/shared.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/i18n/i18n_html_parser.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/i18n/expander.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/directive_normalizer.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/xhr.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/compiler.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/runtime_compiler.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/output/interpretive_view.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/output/output_interpreter.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/output/dart_emitter.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/facade/async.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/facade/promise.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/output/output_jit.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/output/abstract_js_emitter.js",
      "npm:@angular/compiler@2.0.0-rc.4/src/offline_compiler.js",
      "npm:@angular/platform-browser-dynamic@2.0.0-rc.4/src/xhr/xhr_cache.js",
      "npm:@angular/platform-browser-dynamic@2.0.0-rc.4/src/facade/exceptions.js",
      "npm:@angular/platform-browser-dynamic@2.0.0-rc.4/src/facade/exception_handler.js",
      "npm:@angular/platform-browser-dynamic@2.0.0-rc.4/src/facade/collection.js",
      "npm:@angular/platform-browser-dynamic@2.0.0-rc.4/src/facade/base_wrapped_exception.js",
      "npm:@angular/platform-browser-dynamic@2.0.0-rc.4/src/facade/async.js",
      "npm:@angular/platform-browser-dynamic@2.0.0-rc.4/core_private.js",
      "npm:@angular/http@2.0.0-rc.4.js",
      "npm:@angular/http@2.0.0-rc.4/index.js",
      "npm:@angular/http@2.0.0-rc.4/http.js",
      "npm:@angular/http@2.0.0-rc.4/src/url_search_params.js",
      "npm:@angular/http@2.0.0-rc.4/src/facade/lang.js",
      "npm:@angular/http@2.0.0-rc.4/src/facade/collection.js",
      "npm:@angular/http@2.0.0-rc.4/src/static_response.js",
      "npm:@angular/http@2.0.0-rc.4/src/http_utils.js",
      "npm:@angular/http@2.0.0-rc.4/src/enums.js",
      "npm:@angular/http@2.0.0-rc.4/src/facade/exceptions.js",
      "npm:@angular/http@2.0.0-rc.4/src/facade/exception_handler.js",
      "npm:@angular/http@2.0.0-rc.4/src/facade/base_wrapped_exception.js",
      "npm:@angular/http@2.0.0-rc.4/src/static_request.js",
      "npm:@angular/http@2.0.0-rc.4/src/headers.js",
      "npm:@angular/http@2.0.0-rc.4/src/interfaces.js",
      "npm:@angular/http@2.0.0-rc.4/src/http.js",
      "npm:@angular/http@2.0.0-rc.4/src/base_request_options.js",
      "npm:@angular/http@2.0.0-rc.4/src/base_response_options.js",
      "npm:@angular/http@2.0.0-rc.4/src/backends/xhr_backend.js",
      "npm:@angular/http@2.0.0-rc.4/src/backends/browser_xhr.js",
      "npm:@angular/http@2.0.0-rc.4/src/backends/jsonp_backend.js",
      "npm:@angular/http@2.0.0-rc.4/src/backends/browser_jsonp.js",
      "npm:@angular/forms@0.2.0.js",
      "npm:@angular/forms@0.2.0/index.js",
      "npm:@angular/forms@0.2.0/src/forms.js",
      "npm:@angular/forms@0.2.0/src/form_providers.js",
      "npm:@angular/forms@0.2.0/src/form_builder.js",
      "npm:@angular/forms@0.2.0/src/model.js",
      "npm:@angular/forms@0.2.0/src/facade/lang.js",
      "npm:@angular/forms@0.2.0/src/facade/collection.js",
      "npm:@angular/forms@0.2.0/src/facade/async.js",
      "npm:@angular/forms@0.2.0/src/facade/promise.js",
      "npm:@angular/forms@0.2.0/src/directives/shared.js",
      "npm:@angular/forms@0.2.0/src/directives/select_multiple_control_value_accessor.js",
      "npm:@angular/forms@0.2.0/src/directives/control_value_accessor.js",
      "npm:@angular/forms@0.2.0/src/directives/select_control_value_accessor.js",
      "npm:@angular/forms@0.2.0/src/directives/radio_control_value_accessor.js",
      "npm:@angular/forms@0.2.0/src/directives/ng_control.js",
      "npm:@angular/forms@0.2.0/src/directives/abstract_control_directive.js",
      "npm:@angular/forms@0.2.0/src/facade/exceptions.js",
      "npm:@angular/forms@0.2.0/src/facade/exception_handler.js",
      "npm:@angular/forms@0.2.0/src/facade/base_wrapped_exception.js",
      "npm:@angular/forms@0.2.0/src/directives/number_value_accessor.js",
      "npm:@angular/forms@0.2.0/src/directives/normalize_validator.js",
      "npm:@angular/forms@0.2.0/src/directives/default_value_accessor.js",
      "npm:@angular/forms@0.2.0/src/directives/checkbox_value_accessor.js",
      "npm:@angular/forms@0.2.0/src/validators.js",
      "npm:@angular/forms@0.2.0/src/directives.js",
      "npm:@angular/forms@0.2.0/src/directives/validators.js",
      "npm:@angular/forms@0.2.0/src/directives/reactive_directives/form_group_name.js",
      "npm:@angular/forms@0.2.0/src/directives/control_container.js",
      "npm:@angular/forms@0.2.0/src/directives/abstract_form_group_directive.js",
      "npm:@angular/forms@0.2.0/src/directives/reactive_directives/form_group_directive.js",
      "npm:@angular/forms@0.2.0/src/directives/reactive_directives/form_control_name.js",
      "npm:@angular/forms@0.2.0/src/directives/reactive_directives/form_control_directive.js",
      "npm:@angular/forms@0.2.0/src/directives/reactive_directives/form_array_name.js",
      "npm:@angular/forms@0.2.0/src/directives/ng_model_group.js",
      "npm:@angular/forms@0.2.0/src/directives/ng_model.js",
      "npm:@angular/forms@0.2.0/src/directives/ng_form.js",
      "npm:@angular/forms@0.2.0/src/directives/ng_control_status.js"
    ]
  },

  packages: {
    "src": {
      "main": "./main.ts",
      "meta": {
        "*.ts": {
          "loader": "ts"
        }
      }
    },
    "src/lib": {
      "defaultExtension": "ts",
      "meta": {
        "*.ts": {
          "loader": "ts"
        }
      }
    },
    "src/app": {
      "defaultExtension": "ts",
      "meta": {
        "*.ts": {
          "loader": "ts"
        }
      }
    },
    "src/javascript": {
      "defaultExtension": "js"
    }
  },

  map: {
    "@angular/common": "npm:@angular/common@2.0.0-rc.4",
    "@angular/compiler": "npm:@angular/compiler@2.0.0-rc.4",
    "@angular/core": "npm:@angular/core@2.0.0-rc.4",
    "@angular/forms": "npm:@angular/forms@0.2.0",
    "@angular/http": "npm:@angular/http@2.0.0-rc.4",
    "@angular/platform-browser": "npm:@angular/platform-browser@2.0.0-rc.4",
    "@angular/platform-browser-dynamic": "npm:@angular/platform-browser-dynamic@2.0.0-rc.4",
    "@angular/router": "npm:@angular/router@3.0.0-beta.2",
    "@angular/router-deprecated": "npm:@angular/router-deprecated@2.0.0-rc.2",
    "@angular/upgrade": "npm:@angular/upgrade@2.0.0-rc.4",
    "core-js": "npm:core-js@2.4.0",
    "jspm/nodelibs-crypto": "github:jspm/nodelibs-crypto@0.1.0",
    "plugin-typescript": "github:frankwallis/plugin-typescript@4.0.16",
    "reflect-metadata": "npm:reflect-metadata@0.1.3",
    "rxjs": "npm:rxjs@5.0.0-beta.9",
    "ts": "github:frankwallis/plugin-typescript@4.0.16",
    "ts-runtime": "npm:babel-runtime@5.8.38",
    "typescript": "npm:typescript@1.8.10",
    "zone.js": "npm:zone.js@0.6.12",
    "github:frankwallis/plugin-typescript@4.0.16": {
      "typescript": "npm:typescript@1.8.10"
    },
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.4.1"
    },
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.6.0"
    },
    "github:jspm/nodelibs-constants@0.1.0": {
      "constants-browserify": "npm:constants-browserify@0.0.1"
    },
    "github:jspm/nodelibs-crypto@0.1.0": {
      "crypto-browserify": "npm:crypto-browserify@3.11.0"
    },
    "github:jspm/nodelibs-events@0.1.1": {
      "events": "npm:events@1.0.2"
    },
    "github:jspm/nodelibs-os@0.1.0": {
      "os-browserify": "npm:os-browserify@0.1.2"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.5"
    },
    "github:jspm/nodelibs-stream@0.1.0": {
      "stream-browserify": "npm:stream-browserify@1.0.0"
    },
    "github:jspm/nodelibs-string_decoder@0.1.0": {
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "github:jspm/nodelibs-vm@0.1.0": {
      "vm-browserify": "npm:vm-browserify@0.0.4"
    },
    "npm:@angular/common@2.0.0-rc.3": {
      "@angular/core": "npm:@angular/core@2.0.0-rc.3",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:@angular/common@2.0.0-rc.4": {
      "@angular/core": "npm:@angular/core@2.0.0-rc.4",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:@angular/compiler@2.0.0-rc.3": {
      "@angular/core": "npm:@angular/core@2.0.0-rc.3",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:@angular/compiler@2.0.0-rc.4": {
      "@angular/core": "npm:@angular/core@2.0.0-rc.4",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:@angular/core@2.0.0-rc.3": {
      "process": "github:jspm/nodelibs-process@0.1.2",
      "rxjs": "npm:rxjs@5.0.0-beta.6",
      "zone.js": "npm:zone.js@0.6.12"
    },
    "npm:@angular/core@2.0.0-rc.4": {
      "process": "github:jspm/nodelibs-process@0.1.2",
      "rxjs": "npm:rxjs@5.0.0-beta.6",
      "zone.js": "npm:zone.js@0.6.12"
    },
    "npm:@angular/forms@0.2.0": {
      "@angular/common": "npm:@angular/common@2.0.0-rc.4",
      "@angular/compiler": "npm:@angular/compiler@2.0.0-rc.4",
      "@angular/core": "npm:@angular/core@2.0.0-rc.4",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:@angular/http@2.0.0-rc.4": {
      "@angular/core": "npm:@angular/core@2.0.0-rc.4",
      "@angular/platform-browser": "npm:@angular/platform-browser@2.0.0-rc.4",
      "rxjs": "npm:rxjs@5.0.0-beta.6"
    },
    "npm:@angular/platform-browser-dynamic@2.0.0-rc.4": {
      "@angular/common": "npm:@angular/common@2.0.0-rc.4",
      "@angular/compiler": "npm:@angular/compiler@2.0.0-rc.4",
      "@angular/core": "npm:@angular/core@2.0.0-rc.4",
      "@angular/platform-browser": "npm:@angular/platform-browser@2.0.0-rc.4",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:@angular/platform-browser@2.0.0-rc.3": {
      "@angular/common": "npm:@angular/common@2.0.0-rc.3",
      "@angular/compiler": "npm:@angular/compiler@2.0.0-rc.3",
      "@angular/core": "npm:@angular/core@2.0.0-rc.3",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:@angular/platform-browser@2.0.0-rc.4": {
      "@angular/common": "npm:@angular/common@2.0.0-rc.4",
      "@angular/compiler": "npm:@angular/compiler@2.0.0-rc.4",
      "@angular/core": "npm:@angular/core@2.0.0-rc.4",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:@angular/router-deprecated@2.0.0-rc.2": {
      "@angular/common": "npm:@angular/common@2.0.0-rc.3",
      "@angular/core": "npm:@angular/core@2.0.0-rc.3",
      "@angular/platform-browser": "npm:@angular/platform-browser@2.0.0-rc.3"
    },
    "npm:@angular/router@3.0.0-beta.2": {
      "@angular/common": "npm:@angular/common@2.0.0-rc.4",
      "@angular/compiler": "npm:@angular/compiler@2.0.0-rc.4",
      "@angular/core": "npm:@angular/core@2.0.0-rc.4",
      "@angular/platform-browser": "npm:@angular/platform-browser@2.0.0-rc.4",
      "@angular/platform-browser-dynamic": "npm:@angular/platform-browser-dynamic@2.0.0-rc.4",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "rxjs": "npm:rxjs@5.0.0-beta.6"
    },
    "npm:@angular/upgrade@2.0.0-rc.4": {
      "@angular/compiler": "npm:@angular/compiler@2.0.0-rc.4",
      "@angular/core": "npm:@angular/core@2.0.0-rc.4",
      "@angular/platform-browser": "npm:@angular/platform-browser@2.0.0-rc.4",
      "@angular/platform-browser-dynamic": "npm:@angular/platform-browser-dynamic@2.0.0-rc.4"
    },
    "npm:asn1.js@4.6.2": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "bn.js": "npm:bn.js@4.11.4",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0",
      "vm": "github:jspm/nodelibs-vm@0.1.0"
    },
    "npm:assert@1.4.1": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "util": "npm:util@0.10.3"
    },
    "npm:babel-runtime@5.8.38": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:bn.js@4.11.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:browserify-aes@1.0.6": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "buffer-xor": "npm:buffer-xor@1.0.3",
      "cipher-base": "npm:cipher-base@1.0.2",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:browserify-cipher@1.0.0": {
      "browserify-aes": "npm:browserify-aes@1.0.6",
      "browserify-des": "npm:browserify-des@1.0.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0"
    },
    "npm:browserify-des@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "cipher-base": "npm:cipher-base@1.0.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "des.js": "npm:des.js@1.0.0",
      "inherits": "npm:inherits@2.0.1"
    },
    "npm:browserify-rsa@4.0.1": {
      "bn.js": "npm:bn.js@4.11.4",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "constants": "github:jspm/nodelibs-constants@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "randombytes": "npm:randombytes@2.0.3"
    },
    "npm:browserify-sign@4.0.0": {
      "bn.js": "npm:bn.js@4.11.4",
      "browserify-rsa": "npm:browserify-rsa@4.0.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "create-hmac": "npm:create-hmac@1.1.4",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "elliptic": "npm:elliptic@6.3.1",
      "inherits": "npm:inherits@2.0.1",
      "parse-asn1": "npm:parse-asn1@5.0.0",
      "stream": "github:jspm/nodelibs-stream@0.1.0"
    },
    "npm:buffer-xor@1.0.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:buffer@3.6.0": {
      "base64-js": "npm:base64-js@0.0.8",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "ieee754": "npm:ieee754@1.1.6",
      "isarray": "npm:isarray@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:cipher-base@1.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "string_decoder": "github:jspm/nodelibs-string_decoder@0.1.0"
    },
    "npm:constants-browserify@0.0.1": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:core-js@2.4.0": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:core-util-is@1.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:create-ecdh@4.0.0": {
      "bn.js": "npm:bn.js@4.11.4",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "elliptic": "npm:elliptic@6.3.1"
    },
    "npm:create-hash@1.1.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "cipher-base": "npm:cipher-base@1.0.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "ripemd160": "npm:ripemd160@1.0.1",
      "sha.js": "npm:sha.js@2.4.5"
    },
    "npm:create-hmac@1.1.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0"
    },
    "npm:crypto-browserify@3.11.0": {
      "browserify-cipher": "npm:browserify-cipher@1.0.0",
      "browserify-sign": "npm:browserify-sign@4.0.0",
      "create-ecdh": "npm:create-ecdh@4.0.0",
      "create-hash": "npm:create-hash@1.1.2",
      "create-hmac": "npm:create-hmac@1.1.4",
      "diffie-hellman": "npm:diffie-hellman@5.0.2",
      "inherits": "npm:inherits@2.0.1",
      "pbkdf2": "npm:pbkdf2@3.0.4",
      "public-encrypt": "npm:public-encrypt@4.0.0",
      "randombytes": "npm:randombytes@2.0.3"
    },
    "npm:des.js@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0"
    },
    "npm:diffie-hellman@5.0.2": {
      "bn.js": "npm:bn.js@4.11.4",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "miller-rabin": "npm:miller-rabin@4.0.0",
      "randombytes": "npm:randombytes@2.0.3",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:elliptic@6.3.1": {
      "bn.js": "npm:bn.js@4.11.4",
      "brorand": "npm:brorand@1.0.5",
      "hash.js": "npm:hash.js@1.0.3",
      "inherits": "npm:inherits@2.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:evp_bytestokey@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0"
    },
    "npm:hash.js@1.0.3": {
      "inherits": "npm:inherits@2.0.1"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:miller-rabin@4.0.0": {
      "bn.js": "npm:bn.js@4.11.4",
      "brorand": "npm:brorand@1.0.5"
    },
    "npm:os-browserify@0.1.2": {
      "os": "github:jspm/nodelibs-os@0.1.0"
    },
    "npm:parse-asn1@5.0.0": {
      "asn1.js": "npm:asn1.js@4.6.2",
      "browserify-aes": "npm:browserify-aes@1.0.6",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0",
      "pbkdf2": "npm:pbkdf2@3.0.4",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:pbkdf2@3.0.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "create-hmac": "npm:create-hmac@1.1.4",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:process@0.11.5": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "vm": "github:jspm/nodelibs-vm@0.1.0"
    },
    "npm:public-encrypt@4.0.0": {
      "bn.js": "npm:bn.js@4.11.4",
      "browserify-rsa": "npm:browserify-rsa@4.0.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "parse-asn1": "npm:parse-asn1@5.0.0",
      "randombytes": "npm:randombytes@2.0.3"
    },
    "npm:randombytes@2.0.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:readable-stream@1.1.14": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "core-util-is": "npm:core-util-is@1.0.2",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "isarray": "npm:isarray@0.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream-browserify": "npm:stream-browserify@1.0.0",
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "npm:reflect-metadata@0.1.3": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:ripemd160@1.0.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:rxjs@5.0.0-beta.6": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:rxjs@5.0.0-beta.9": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "symbol-observable": "npm:symbol-observable@0.2.4"
    },
    "npm:sha.js@2.4.5": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:stream-browserify@1.0.0": {
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "readable-stream": "npm:readable-stream@1.1.14"
    },
    "npm:string_decoder@0.10.31": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:typescript@1.8.10": {
      "os": "github:jspm/nodelibs-os@0.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:vm-browserify@0.0.4": {
      "indexof": "npm:indexof@0.0.1"
    },
    "npm:zone.js@0.6.12": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    }
  }
});
