System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: "typescript",
  typescriptOptions: {
    "tsconfig": true
  },
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  bundles: {
    ".dev/vendor.js": [
      "npm:rxjs@5.0.0-beta.7/Rx.js",
      "github:jspm/nodelibs-process@0.1.2.js",
      "github:jspm/nodelibs-process@0.1.2/index.js",
      "npm:process@0.11.3.js",
      "npm:process@0.11.3/browser.js",
      "npm:symbol-observable@0.2.4.js",
      "npm:symbol-observable@0.2.4/index.js",
      "npm:symbol-observable@0.2.4/ponyfill.js",
      "npm:rxjs@5.0.0-beta.7/symbol/iterator.js",
      "npm:rxjs@5.0.0-beta.7/util/root.js",
      "npm:rxjs@5.0.0-beta.7/symbol/rxSubscriber.js",
      "npm:rxjs@5.0.0-beta.7/scheduler/queue.js",
      "npm:rxjs@5.0.0-beta.7/scheduler/QueueScheduler.js",
      "npm:rxjs@5.0.0-beta.7/scheduler/FutureAction.js",
      "npm:rxjs@5.0.0-beta.7/Subscription.js",
      "npm:rxjs@5.0.0-beta.7/util/UnsubscriptionError.js",
      "npm:rxjs@5.0.0-beta.7/util/errorObject.js",
      "npm:rxjs@5.0.0-beta.7/util/tryCatch.js",
      "npm:rxjs@5.0.0-beta.7/util/isFunction.js",
      "npm:rxjs@5.0.0-beta.7/util/isObject.js",
      "npm:rxjs@5.0.0-beta.7/util/isArray.js",
      "npm:rxjs@5.0.0-beta.7/scheduler/QueueAction.js",
      "npm:rxjs@5.0.0-beta.7/scheduler/async.js",
      "npm:rxjs@5.0.0-beta.7/scheduler/AsyncScheduler.js",
      "npm:rxjs@5.0.0-beta.7/scheduler/asap.js",
      "npm:rxjs@5.0.0-beta.7/scheduler/AsapScheduler.js",
      "npm:rxjs@5.0.0-beta.7/scheduler/AsapAction.js",
      "npm:rxjs@5.0.0-beta.7/util/Immediate.js",
      "npm:rxjs@5.0.0-beta.7/util/ObjectUnsubscribedError.js",
      "npm:rxjs@5.0.0-beta.7/util/ArgumentOutOfRangeError.js",
      "npm:rxjs@5.0.0-beta.7/util/EmptyError.js",
      "npm:rxjs@5.0.0-beta.7/Notification.js",
      "npm:rxjs@5.0.0-beta.7/Observable.js",
      "npm:rxjs@5.0.0-beta.7/util/toSubscriber.js",
      "npm:rxjs@5.0.0-beta.7/Subscriber.js",
      "npm:rxjs@5.0.0-beta.7/Observer.js",
      "npm:rxjs@5.0.0-beta.7/observable/ConnectableObservable.js",
      "npm:rxjs@5.0.0-beta.7/BehaviorSubject.js",
      "npm:rxjs@5.0.0-beta.7/util/throwError.js",
      "npm:rxjs@5.0.0-beta.7/Subject.js",
      "npm:rxjs@5.0.0-beta.7/SubjectSubscription.js",
      "npm:rxjs@5.0.0-beta.7/ReplaySubject.js",
      "npm:rxjs@5.0.0-beta.7/operator/observeOn.js",
      "npm:rxjs@5.0.0-beta.7/AsyncSubject.js",
      "npm:rxjs@5.0.0-beta.7/Operator.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/zipAll.js",
      "npm:rxjs@5.0.0-beta.7/operator/zipAll.js",
      "npm:rxjs@5.0.0-beta.7/operator/zip.js",
      "npm:rxjs@5.0.0-beta.7/util/subscribeToResult.js",
      "npm:rxjs@5.0.0-beta.7/InnerSubscriber.js",
      "npm:rxjs@5.0.0-beta.7/util/isPromise.js",
      "npm:rxjs@5.0.0-beta.7/OuterSubscriber.js",
      "npm:rxjs@5.0.0-beta.7/observable/ArrayObservable.js",
      "npm:rxjs@5.0.0-beta.7/util/isScheduler.js",
      "npm:rxjs@5.0.0-beta.7/observable/EmptyObservable.js",
      "npm:rxjs@5.0.0-beta.7/observable/ScalarObservable.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/zip.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/withLatestFrom.js",
      "npm:rxjs@5.0.0-beta.7/operator/withLatestFrom.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/windowWhen.js",
      "npm:rxjs@5.0.0-beta.7/operator/windowWhen.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/windowToggle.js",
      "npm:rxjs@5.0.0-beta.7/operator/windowToggle.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/windowTime.js",
      "npm:rxjs@5.0.0-beta.7/operator/windowTime.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/windowCount.js",
      "npm:rxjs@5.0.0-beta.7/operator/windowCount.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/window.js",
      "npm:rxjs@5.0.0-beta.7/operator/window.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/toPromise.js",
      "npm:rxjs@5.0.0-beta.7/operator/toPromise.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/toArray.js",
      "npm:rxjs@5.0.0-beta.7/operator/toArray.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/timeoutWith.js",
      "npm:rxjs@5.0.0-beta.7/operator/timeoutWith.js",
      "npm:rxjs@5.0.0-beta.7/util/isDate.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/timeout.js",
      "npm:rxjs@5.0.0-beta.7/operator/timeout.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/throttleTime.js",
      "npm:rxjs@5.0.0-beta.7/operator/throttleTime.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/throttle.js",
      "npm:rxjs@5.0.0-beta.7/operator/throttle.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/takeWhile.js",
      "npm:rxjs@5.0.0-beta.7/operator/takeWhile.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/takeUntil.js",
      "npm:rxjs@5.0.0-beta.7/operator/takeUntil.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/takeLast.js",
      "npm:rxjs@5.0.0-beta.7/operator/takeLast.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/take.js",
      "npm:rxjs@5.0.0-beta.7/operator/take.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/switchMapTo.js",
      "npm:rxjs@5.0.0-beta.7/operator/switchMapTo.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/switchMap.js",
      "npm:rxjs@5.0.0-beta.7/operator/switchMap.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/switch.js",
      "npm:rxjs@5.0.0-beta.7/operator/switch.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/subscribeOn.js",
      "npm:rxjs@5.0.0-beta.7/operator/subscribeOn.js",
      "npm:rxjs@5.0.0-beta.7/observable/SubscribeOnObservable.js",
      "npm:rxjs@5.0.0-beta.7/util/isNumeric.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/startWith.js",
      "npm:rxjs@5.0.0-beta.7/operator/startWith.js",
      "npm:rxjs@5.0.0-beta.7/operator/concat.js",
      "npm:rxjs@5.0.0-beta.7/operator/mergeAll.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/skipWhile.js",
      "npm:rxjs@5.0.0-beta.7/operator/skipWhile.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/skipUntil.js",
      "npm:rxjs@5.0.0-beta.7/operator/skipUntil.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/skip.js",
      "npm:rxjs@5.0.0-beta.7/operator/skip.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/single.js",
      "npm:rxjs@5.0.0-beta.7/operator/single.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/share.js",
      "npm:rxjs@5.0.0-beta.7/operator/share.js",
      "npm:rxjs@5.0.0-beta.7/operator/multicast.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/scan.js",
      "npm:rxjs@5.0.0-beta.7/operator/scan.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/sampleTime.js",
      "npm:rxjs@5.0.0-beta.7/operator/sampleTime.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/sample.js",
      "npm:rxjs@5.0.0-beta.7/operator/sample.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/retryWhen.js",
      "npm:rxjs@5.0.0-beta.7/operator/retryWhen.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/retry.js",
      "npm:rxjs@5.0.0-beta.7/operator/retry.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/repeat.js",
      "npm:rxjs@5.0.0-beta.7/operator/repeat.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/reduce.js",
      "npm:rxjs@5.0.0-beta.7/operator/reduce.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/race.js",
      "npm:rxjs@5.0.0-beta.7/operator/race.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/publishLast.js",
      "npm:rxjs@5.0.0-beta.7/operator/publishLast.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/publishReplay.js",
      "npm:rxjs@5.0.0-beta.7/operator/publishReplay.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/publishBehavior.js",
      "npm:rxjs@5.0.0-beta.7/operator/publishBehavior.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/publish.js",
      "npm:rxjs@5.0.0-beta.7/operator/publish.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/pluck.js",
      "npm:rxjs@5.0.0-beta.7/operator/pluck.js",
      "npm:rxjs@5.0.0-beta.7/operator/map.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/partition.js",
      "npm:rxjs@5.0.0-beta.7/operator/partition.js",
      "npm:rxjs@5.0.0-beta.7/operator/filter.js",
      "npm:rxjs@5.0.0-beta.7/util/not.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/observeOn.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/multicast.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/mergeMapTo.js",
      "npm:rxjs@5.0.0-beta.7/operator/mergeMapTo.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/mergeMap.js",
      "npm:rxjs@5.0.0-beta.7/operator/mergeMap.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/mergeAll.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/merge.js",
      "npm:rxjs@5.0.0-beta.7/operator/merge.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/materialize.js",
      "npm:rxjs@5.0.0-beta.7/operator/materialize.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/mapTo.js",
      "npm:rxjs@5.0.0-beta.7/operator/mapTo.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/map.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/every.js",
      "npm:rxjs@5.0.0-beta.7/operator/every.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/let.js",
      "npm:rxjs@5.0.0-beta.7/operator/let.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/last.js",
      "npm:rxjs@5.0.0-beta.7/operator/last.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/auditTime.js",
      "npm:rxjs@5.0.0-beta.7/operator/auditTime.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/audit.js",
      "npm:rxjs@5.0.0-beta.7/operator/audit.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/ignoreElements.js",
      "npm:rxjs@5.0.0-beta.7/operator/ignoreElements.js",
      "npm:rxjs@5.0.0-beta.7/util/noop.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/groupBy.js",
      "npm:rxjs@5.0.0-beta.7/operator/groupBy.js",
      "npm:rxjs@5.0.0-beta.7/util/FastMap.js",
      "npm:rxjs@5.0.0-beta.7/util/Map.js",
      "npm:rxjs@5.0.0-beta.7/util/MapPolyfill.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/first.js",
      "npm:rxjs@5.0.0-beta.7/operator/first.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/finally.js",
      "npm:rxjs@5.0.0-beta.7/operator/finally.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/filter.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/expand.js",
      "npm:rxjs@5.0.0-beta.7/operator/expand.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/do.js",
      "npm:rxjs@5.0.0-beta.7/operator/do.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/distinctUntilChanged.js",
      "npm:rxjs@5.0.0-beta.7/operator/distinctUntilChanged.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/delayWhen.js",
      "npm:rxjs@5.0.0-beta.7/operator/delayWhen.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/delay.js",
      "npm:rxjs@5.0.0-beta.7/operator/delay.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/defaultIfEmpty.js",
      "npm:rxjs@5.0.0-beta.7/operator/defaultIfEmpty.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/debounceTime.js",
      "npm:rxjs@5.0.0-beta.7/operator/debounceTime.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/debounce.js",
      "npm:rxjs@5.0.0-beta.7/operator/debounce.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/dematerialize.js",
      "npm:rxjs@5.0.0-beta.7/operator/dematerialize.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/count.js",
      "npm:rxjs@5.0.0-beta.7/operator/count.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/concatMapTo.js",
      "npm:rxjs@5.0.0-beta.7/operator/concatMapTo.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/concatMap.js",
      "npm:rxjs@5.0.0-beta.7/operator/concatMap.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/concatAll.js",
      "npm:rxjs@5.0.0-beta.7/operator/concatAll.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/concat.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/combineLatest.js",
      "npm:rxjs@5.0.0-beta.7/operator/combineLatest.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/combineAll.js",
      "npm:rxjs@5.0.0-beta.7/operator/combineAll.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/catch.js",
      "npm:rxjs@5.0.0-beta.7/operator/catch.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/cache.js",
      "npm:rxjs@5.0.0-beta.7/operator/cache.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/bufferWhen.js",
      "npm:rxjs@5.0.0-beta.7/operator/bufferWhen.js",
      "github:jspm/nodelibs-buffer@0.1.0.js",
      "github:jspm/nodelibs-buffer@0.1.0/index.js",
      "npm:buffer@3.6.0.js",
      "npm:buffer@3.6.0/index.js",
      "npm:isarray@1.0.0.js",
      "npm:isarray@1.0.0/index.js",
      "npm:ieee754@1.1.6.js",
      "npm:ieee754@1.1.6/index.js",
      "npm:base64-js@0.0.8.js",
      "npm:base64-js@0.0.8/lib/b64.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/bufferToggle.js",
      "npm:rxjs@5.0.0-beta.7/operator/bufferToggle.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/bufferTime.js",
      "npm:rxjs@5.0.0-beta.7/operator/bufferTime.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/bufferCount.js",
      "npm:rxjs@5.0.0-beta.7/operator/bufferCount.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/buffer.js",
      "npm:rxjs@5.0.0-beta.7/operator/buffer.js",
      "npm:rxjs@5.0.0-beta.7/add/observable/zip.js",
      "npm:rxjs@5.0.0-beta.7/observable/zip.js",
      "npm:rxjs@5.0.0-beta.7/add/observable/timer.js",
      "npm:rxjs@5.0.0-beta.7/observable/timer.js",
      "npm:rxjs@5.0.0-beta.7/observable/TimerObservable.js",
      "npm:rxjs@5.0.0-beta.7/add/observable/throw.js",
      "npm:rxjs@5.0.0-beta.7/observable/throw.js",
      "npm:rxjs@5.0.0-beta.7/observable/ErrorObservable.js",
      "npm:rxjs@5.0.0-beta.7/add/observable/range.js",
      "npm:rxjs@5.0.0-beta.7/observable/range.js",
      "npm:rxjs@5.0.0-beta.7/observable/RangeObservable.js",
      "npm:rxjs@5.0.0-beta.7/add/observable/of.js",
      "npm:rxjs@5.0.0-beta.7/observable/of.js",
      "npm:rxjs@5.0.0-beta.7/add/observable/never.js",
      "npm:rxjs@5.0.0-beta.7/observable/never.js",
      "npm:rxjs@5.0.0-beta.7/observable/NeverObservable.js",
      "npm:rxjs@5.0.0-beta.7/add/observable/race.js",
      "npm:rxjs@5.0.0-beta.7/add/observable/merge.js",
      "npm:rxjs@5.0.0-beta.7/observable/merge.js",
      "npm:rxjs@5.0.0-beta.7/add/observable/interval.js",
      "npm:rxjs@5.0.0-beta.7/observable/interval.js",
      "npm:rxjs@5.0.0-beta.7/observable/IntervalObservable.js",
      "npm:rxjs@5.0.0-beta.7/add/observable/generate.js",
      "npm:rxjs@5.0.0-beta.7/observable/GenerateObservable.js",
      "npm:rxjs@5.0.0-beta.7/add/observable/fromPromise.js",
      "npm:rxjs@5.0.0-beta.7/observable/fromPromise.js",
      "npm:rxjs@5.0.0-beta.7/observable/PromiseObservable.js",
      "npm:rxjs@5.0.0-beta.7/add/observable/fromEventPattern.js",
      "npm:rxjs@5.0.0-beta.7/observable/fromEventPattern.js",
      "npm:rxjs@5.0.0-beta.7/observable/FromEventPatternObservable.js",
      "npm:rxjs@5.0.0-beta.7/add/observable/fromEvent.js",
      "npm:rxjs@5.0.0-beta.7/observable/fromEvent.js",
      "npm:rxjs@5.0.0-beta.7/observable/FromEventObservable.js",
      "npm:rxjs@5.0.0-beta.7/add/observable/from.js",
      "npm:rxjs@5.0.0-beta.7/observable/from.js",
      "npm:rxjs@5.0.0-beta.7/observable/FromObservable.js",
      "npm:rxjs@5.0.0-beta.7/observable/ArrayLikeObservable.js",
      "npm:rxjs@5.0.0-beta.7/observable/IteratorObservable.js",
      "npm:rxjs@5.0.0-beta.7/add/observable/forkJoin.js",
      "npm:rxjs@5.0.0-beta.7/observable/forkJoin.js",
      "npm:rxjs@5.0.0-beta.7/observable/ForkJoinObservable.js",
      "npm:rxjs@5.0.0-beta.7/add/observable/empty.js",
      "npm:rxjs@5.0.0-beta.7/observable/empty.js",
      "npm:rxjs@5.0.0-beta.7/add/observable/defer.js",
      "npm:rxjs@5.0.0-beta.7/observable/defer.js",
      "npm:rxjs@5.0.0-beta.7/observable/DeferObservable.js",
      "npm:rxjs@5.0.0-beta.7/add/observable/concat.js",
      "npm:rxjs@5.0.0-beta.7/observable/concat.js",
      "npm:rxjs@5.0.0-beta.7/add/observable/combineLatest.js",
      "npm:rxjs@5.0.0-beta.7/add/observable/bindNodeCallback.js",
      "npm:rxjs@5.0.0-beta.7/observable/bindNodeCallback.js",
      "npm:rxjs@5.0.0-beta.7/observable/BoundNodeCallbackObservable.js",
      "npm:rxjs@5.0.0-beta.7/add/observable/bindCallback.js",
      "npm:rxjs@5.0.0-beta.7/observable/bindCallback.js",
      "npm:rxjs@5.0.0-beta.7/observable/BoundCallbackObservable.js",
      "npm:angular2@2.0.0-beta.17/router.js",
      "npm:zone.js@0.6.12/dist/zone.js",
      "npm:reflect-metadata@0.1.2.js",
      "npm:reflect-metadata@0.1.2/Reflect.js",
      "github:es-shims/es6-shim@0.35.0.js",
      "github:es-shims/es6-shim@0.35.0/es6-shim.js",
      "npm:angular2@2.0.0-beta.17/src/facade/lang.js",
      "npm:angular2@2.0.0-beta.17/src/router/router_providers.js",
      "npm:angular2@2.0.0-beta.17/platform/common.js",
      "npm:angular2@2.0.0-beta.17/src/platform/location.js",
      "npm:angular2@2.0.0-beta.17/src/platform/browser/location/location.js",
      "npm:angular2@2.0.0-beta.17/src/platform/browser/location/location_strategy.js",
      "npm:angular2@2.0.0-beta.17/core.js",
      "npm:angular2@2.0.0-beta.17/src/core/reflection/reflection.js",
      "npm:angular2@2.0.0-beta.17/src/core/reflection/reflection_capabilities.js",
      "npm:angular2@2.0.0-beta.17/src/facade/exceptions.js",
      "npm:angular2@2.0.0-beta.17/src/facade/exception_handler.js",
      "npm:angular2@2.0.0-beta.17/src/facade/collection.js",
      "npm:angular2@2.0.0-beta.17/src/facade/base_wrapped_exception.js",
      "npm:angular2@2.0.0-beta.17/src/core/reflection/reflector.js",
      "npm:angular2@2.0.0-beta.17/src/core/reflection/reflector_reader.js",
      "npm:angular2@2.0.0-beta.17/src/core/application_common_providers.js",
      "npm:angular2@2.0.0-beta.17/src/core/linker/dynamic_component_loader.js",
      "npm:angular2@2.0.0-beta.17/src/core/linker/component_resolver.js",
      "npm:angular2@2.0.0-beta.17/src/core/linker/component_factory.js",
      "npm:angular2@2.0.0-beta.17/src/core/linker/view_utils.js",
      "npm:angular2@2.0.0-beta.17/src/core/application_tokens.js",
      "npm:angular2@2.0.0-beta.17/src/core/di.js",
      "npm:angular2@2.0.0-beta.17/src/core/di/opaque_token.js",
      "npm:angular2@2.0.0-beta.17/src/core/di/reflective_exceptions.js",
      "npm:angular2@2.0.0-beta.17/src/core/di/reflective_key.js",
      "npm:angular2@2.0.0-beta.17/src/core/di/forward_ref.js",
      "npm:angular2@2.0.0-beta.17/src/core/di/reflective_provider.js",
      "npm:angular2@2.0.0-beta.17/src/core/di/provider.js",
      "npm:angular2@2.0.0-beta.17/src/core/di/metadata.js",
      "npm:angular2@2.0.0-beta.17/src/core/di/reflective_injector.js",
      "npm:angular2@2.0.0-beta.17/src/core/di/injector.js",
      "npm:angular2@2.0.0-beta.17/src/core/di/decorators.js",
      "npm:angular2@2.0.0-beta.17/src/core/util/decorators.js",
      "npm:angular2@2.0.0-beta.17/src/core/render/api.js",
      "npm:angular2@2.0.0-beta.17/src/core/change_detection/change_detection.js",
      "npm:angular2@2.0.0-beta.17/src/core/change_detection/change_detection_util.js",
      "npm:angular2@2.0.0-beta.17/src/core/change_detection/change_detector_ref.js",
      "npm:angular2@2.0.0-beta.17/src/core/change_detection/constants.js",
      "npm:angular2@2.0.0-beta.17/src/core/change_detection/differs/default_keyvalue_differ.js",
      "npm:angular2@2.0.0-beta.17/src/core/change_detection/differs/keyvalue_differs.js",
      "npm:angular2@2.0.0-beta.17/src/core/change_detection/differs/default_iterable_differ.js",
      "npm:angular2@2.0.0-beta.17/src/core/change_detection/differs/iterable_differs.js",
      "npm:angular2@2.0.0-beta.17/src/core/linker/exceptions.js",
      "npm:angular2@2.0.0-beta.17/src/core/linker/element.js",
      "npm:angular2@2.0.0-beta.17/src/core/linker/view_container_ref.js",
      "npm:angular2@2.0.0-beta.17/src/core/profile/profile.js",
      "npm:angular2@2.0.0-beta.17/src/core/profile/wtf_impl.js",
      "npm:angular2@2.0.0-beta.17/src/core/linker/element_ref.js",
      "npm:angular2@2.0.0-beta.17/src/core/linker/view_type.js",
      "npm:angular2@2.0.0-beta.17/src/facade/async.js",
      "npm:angular2@2.0.0-beta.17/src/facade/promise.js",
      "npm:angular2@2.0.0-beta.17/src/core/application_ref.js",
      "npm:angular2@2.0.0-beta.17/src/core/console.js",
      "npm:angular2@2.0.0-beta.17/src/core/testability/testability.js",
      "npm:angular2@2.0.0-beta.17/src/core/zone/ng_zone.js",
      "npm:angular2@2.0.0-beta.17/src/core/zone/ng_zone_impl.js",
      "npm:angular2@2.0.0-beta.17/src/core/platform_common_providers.js",
      "npm:angular2@2.0.0-beta.17/src/core/platform_directives_and_pipes.js",
      "npm:angular2@2.0.0-beta.17/src/core/change_detection.js",
      "npm:angular2@2.0.0-beta.17/src/core/debug/debug_node.js",
      "npm:angular2@2.0.0-beta.17/src/core/linker.js",
      "npm:angular2@2.0.0-beta.17/src/core/linker/view_ref.js",
      "npm:angular2@2.0.0-beta.17/src/core/linker/template_ref.js",
      "npm:angular2@2.0.0-beta.17/src/core/linker/query_list.js",
      "npm:angular2@2.0.0-beta.17/src/core/render.js",
      "npm:angular2@2.0.0-beta.17/src/core/zone.js",
      "npm:angular2@2.0.0-beta.17/src/facade/facade.js",
      "npm:angular2@2.0.0-beta.17/src/core/prod_mode.js",
      "npm:angular2@2.0.0-beta.17/src/core/util.js",
      "npm:angular2@2.0.0-beta.17/src/core/metadata.js",
      "npm:angular2@2.0.0-beta.17/src/core/metadata/view.js",
      "npm:angular2@2.0.0-beta.17/src/core/metadata/directives.js",
      "npm:angular2@2.0.0-beta.17/src/core/metadata/di.js",
      "npm:angular2@2.0.0-beta.17/src/platform/browser/location/path_location_strategy.js",
      "npm:angular2@2.0.0-beta.17/src/platform/browser/location/platform_location.js",
      "npm:angular2@2.0.0-beta.17/src/platform/browser/location/hash_location_strategy.js",
      "npm:angular2@2.0.0-beta.17/src/platform/browser/location/browser_platform_location.js",
      "npm:angular2@2.0.0-beta.17/src/platform/dom/dom_adapter.js",
      "npm:angular2@2.0.0-beta.17/src/router/router_providers_common.js",
      "npm:angular2@2.0.0-beta.17/src/router/route_registry.js",
      "npm:angular2@2.0.0-beta.17/src/router/url_parser.js",
      "npm:angular2@2.0.0-beta.17/src/router/route_config/route_config_normalizer.js",
      "npm:angular2@2.0.0-beta.17/src/router/route_config/route_config_decorator.js",
      "npm:angular2@2.0.0-beta.17/src/router/route_config/route_config_impl.js",
      "npm:angular2@2.0.0-beta.17/src/router/instruction.js",
      "npm:angular2@2.0.0-beta.17/src/router/rules/rule_set.js",
      "npm:angular2@2.0.0-beta.17/src/router/rules/route_paths/regex_route_path.js",
      "npm:angular2@2.0.0-beta.17/src/router/rules/route_paths/route_path.js",
      "npm:angular2@2.0.0-beta.17/src/router/rules/route_paths/param_route_path.js",
      "npm:angular2@2.0.0-beta.17/src/router/utils.js",
      "npm:angular2@2.0.0-beta.17/src/router/rules/route_handlers/sync_route_handler.js",
      "npm:angular2@2.0.0-beta.17/src/router/rules/route_handlers/async_route_handler.js",
      "npm:angular2@2.0.0-beta.17/src/router/rules/rules.js",
      "npm:angular2@2.0.0-beta.17/src/router/router.js",
      "npm:angular2@2.0.0-beta.17/src/router/lifecycle/route_lifecycle_reflector.js",
      "npm:angular2@2.0.0-beta.17/src/router/lifecycle/lifecycle_annotations_impl.js",
      "npm:angular2@2.0.0-beta.17/src/router/lifecycle/lifecycle_annotations.js",
      "npm:angular2@2.0.0-beta.17/src/router/directives/router_link.js",
      "npm:angular2@2.0.0-beta.17/src/router/directives/router_outlet.js",
      "npm:angular2@2.0.0-beta.17/platform/browser.js",
      "npm:angular2@2.0.0-beta.17/src/platform/browser/xhr_impl.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/xhr.js",
      "npm:angular2@2.0.0-beta.17/compiler.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/template_ast.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/compiler.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/expression_parser/lexer.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/expression_parser/parser.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/expression_parser/ast.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/schema/dom_element_schema_registry.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/schema/element_schema_registry.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/html_tags.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/runtime_compiler.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/output/interpretive_view.js",
      "npm:angular2@2.0.0-beta.17/src/core/linker/view.js",
      "npm:angular2@2.0.0-beta.17/src/core/linker/element_injector.js",
      "npm:angular2@2.0.0-beta.17/src/core/linker/debug_context.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/output/output_interpreter.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/output/ts_emitter.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/output/path_util.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/output/abstract_emitter.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/output/output_ast.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/output/dart_emitter.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/output/output_jit.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/util.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/output/abstract_js_emitter.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/config.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/identifiers.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/compile_metadata.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/url_resolver.js",
      "npm:angular2@2.0.0-beta.17/src/core/metadata/lifecycle_hooks.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/selector.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/runtime_metadata.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/assertions.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/directive_lifecycle_reflector.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/view_resolver.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/pipe_resolver.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/directive_resolver.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/directive_normalizer.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/template_preparser.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/html_parser.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/parse_util.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/html_lexer.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/html_ast.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/style_url_resolver.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/template_parser.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/provider_parser.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/view_compiler/view_compiler.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/view_compiler/view_binder.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/view_compiler/lifecycle_binder.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/view_compiler/constants.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/view_compiler/event_binder.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/view_compiler/compile_binding.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/view_compiler/expression_converter.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/view_compiler/compile_method.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/view_compiler/property_binder.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/view_compiler/view_builder.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/view_compiler/util.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/view_compiler/compile_element.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/view_compiler/compile_query.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/view_compiler/compile_view.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/view_compiler/compile_pipe.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/style_compiler.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/shadow_css.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/offline_compiler.js",
      "npm:angular2@2.0.0-beta.17/src/platform/browser_common.js",
      "npm:angular2@2.0.0-beta.17/src/platform/dom/events/hammer_gestures.js",
      "npm:angular2@2.0.0-beta.17/src/platform/dom/events/hammer_common.js",
      "npm:angular2@2.0.0-beta.17/src/platform/dom/events/event_manager.js",
      "npm:angular2@2.0.0-beta.17/src/platform/browser/tools/tools.js",
      "npm:angular2@2.0.0-beta.17/src/platform/browser/tools/common_tools.js",
      "npm:angular2@2.0.0-beta.17/src/facade/browser.js",
      "npm:angular2@2.0.0-beta.17/src/platform/browser/title.js",
      "npm:angular2@2.0.0-beta.17/platform/common_dom.js",
      "npm:angular2@2.0.0-beta.17/src/platform/dom/debug/ng_probe.js",
      "npm:angular2@2.0.0-beta.17/src/core/debug/debug_renderer.js",
      "npm:angular2@2.0.0-beta.17/src/platform/dom/dom_renderer.js",
      "npm:angular2@2.0.0-beta.17/src/platform/dom/util.js",
      "npm:angular2@2.0.0-beta.17/src/platform/dom/dom_tokens.js",
      "npm:angular2@2.0.0-beta.17/src/platform/dom/shared_styles_host.js",
      "npm:angular2@2.0.0-beta.17/src/animate/animation_builder.js",
      "npm:angular2@2.0.0-beta.17/src/animate/browser_details.js",
      "npm:angular2@2.0.0-beta.17/src/facade/math.js",
      "npm:angular2@2.0.0-beta.17/src/animate/css_animation_builder.js",
      "npm:angular2@2.0.0-beta.17/src/animate/animation.js",
      "npm:angular2@2.0.0-beta.17/src/animate/css_animation_options.js",
      "npm:angular2@2.0.0-beta.17/src/platform/dom/debug/by.js",
      "npm:angular2@2.0.0-beta.17/src/platform/dom/events/dom_events.js",
      "npm:angular2@2.0.0-beta.17/src/core/profile/wtf_init.js",
      "npm:angular2@2.0.0-beta.17/src/platform/browser/xhr_cache.js",
      "npm:angular2@2.0.0-beta.17/src/platform/browser/testability.js",
      "npm:angular2@2.0.0-beta.17/src/platform/browser/browser_adapter.js",
      "npm:angular2@2.0.0-beta.17/src/platform/browser/generic_browser_adapter.js",
      "npm:angular2@2.0.0-beta.17/src/platform/dom/events/key_events.js",
      "npm:angular2@2.0.0-beta.17/common.js",
      "npm:angular2@2.0.0-beta.17/src/common/common_directives.js",
      "npm:angular2@2.0.0-beta.17/src/common/directives.js",
      "npm:angular2@2.0.0-beta.17/src/common/directives/core_directives.js",
      "npm:angular2@2.0.0-beta.17/src/common/directives/ng_plural.js",
      "npm:angular2@2.0.0-beta.17/src/common/directives/ng_switch.js",
      "npm:angular2@2.0.0-beta.17/src/common/directives/ng_style.js",
      "npm:angular2@2.0.0-beta.17/src/common/directives/ng_template_outlet.js",
      "npm:angular2@2.0.0-beta.17/src/common/directives/ng_if.js",
      "npm:angular2@2.0.0-beta.17/src/common/directives/ng_for.js",
      "npm:angular2@2.0.0-beta.17/src/common/directives/ng_class.js",
      "npm:angular2@2.0.0-beta.17/src/common/directives/observable_list_diff.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/directives/radio_control_value_accessor.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/directives/ng_control.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/directives/abstract_control_directive.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/directives/control_value_accessor.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/form_builder.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/model.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/directives/validators.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/validators.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/directives.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/directives/select_control_value_accessor.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/directives/ng_control_status.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/directives/number_value_accessor.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/directives/checkbox_value_accessor.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/directives/default_value_accessor.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/directives/ng_form.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/directives/shared.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/directives/normalize_validator.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/directives/control_container.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/directives/ng_form_model.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/directives/ng_control_group.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/directives/ng_model.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/directives/ng_form_control.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/directives/ng_control_name.js",
      "npm:angular2@2.0.0-beta.17/src/common/pipes.js",
      "npm:angular2@2.0.0-beta.17/src/common/pipes/common_pipes.js",
      "npm:angular2@2.0.0-beta.17/src/common/pipes/i18n_select_pipe.js",
      "npm:angular2@2.0.0-beta.17/src/common/pipes/invalid_pipe_argument_exception.js",
      "npm:angular2@2.0.0-beta.17/src/common/pipes/i18n_plural_pipe.js",
      "npm:angular2@2.0.0-beta.17/src/common/pipes/replace_pipe.js",
      "npm:angular2@2.0.0-beta.17/src/common/pipes/number_pipe.js",
      "npm:angular2@2.0.0-beta.17/src/facade/intl.js",
      "npm:angular2@2.0.0-beta.17/src/common/pipes/date_pipe.js",
      "npm:angular2@2.0.0-beta.17/src/common/pipes/slice_pipe.js",
      "npm:angular2@2.0.0-beta.17/src/common/pipes/json_pipe.js",
      "npm:angular2@2.0.0-beta.17/src/common/pipes/lowercase_pipe.js",
      "npm:angular2@2.0.0-beta.17/src/common/pipes/uppercase_pipe.js",
      "npm:angular2@2.0.0-beta.17/src/common/pipes/async_pipe.js",
      "npm:angular2@2.0.0-beta.17/http.js",
      "npm:angular2@2.0.0-beta.17/src/http/url_search_params.js",
      "npm:angular2@2.0.0-beta.17/src/http/enums.js",
      "npm:angular2@2.0.0-beta.17/src/http/headers.js",
      "npm:angular2@2.0.0-beta.17/src/http/interfaces.js",
      "npm:angular2@2.0.0-beta.17/src/http/static_response.js",
      "npm:angular2@2.0.0-beta.17/src/http/http_utils.js",
      "npm:angular2@2.0.0-beta.17/src/http/static_request.js",
      "npm:angular2@2.0.0-beta.17/src/http/base_response_options.js",
      "npm:angular2@2.0.0-beta.17/src/http/base_request_options.js",
      "npm:angular2@2.0.0-beta.17/src/http/backends/browser_jsonp.js",
      "npm:angular2@2.0.0-beta.17/src/http/backends/browser_xhr.js",
      "npm:angular2@2.0.0-beta.17/src/http/backends/jsonp_backend.js",
      "npm:angular2@2.0.0-beta.17/src/http/backends/xhr_backend.js",
      "npm:angular2@2.0.0-beta.17/src/http/http.js",
      "npm:angular2@2.0.0-beta.17/bundles/angular2-polyfills.js"
    ]
  },

  packages: {
    "src": {
      "main": "./main.ts",
      "meta": {
        "*.ts": {
          "loader": "ts"
        }
      }
    },
    "src/lib": {
      "defaultExtension": "ts",
      "meta": {
        "*.ts": {
          "loader": "ts"
        }
      }
    },
    "src/app": {
      "defaultExtension": "ts",
      "meta": {
        "*.ts": {
          "loader": "ts"
        }
      }
    },
    "src/javascript": {
      "defaultExtension": "js"
    }
  },

  meta: {
    "npm:angular2@2.0.0-beta.17/*": {
      "deps": [
        "es6-shim",
        "reflect-metadata",
        "zone.js/dist/zone.js"
      ]
    }
  },

  map: {
    "angular2": "npm:angular2@2.0.0-beta.17",
    "es6-shim": "github:es-shims/es6-shim@0.35.0",
    "plugin-typescript": "github:frankwallis/plugin-typescript@4.0.10",
    "reflect-metadata": "npm:reflect-metadata@0.1.3",
    "rxjs": "npm:rxjs@5.0.0-beta.7",
    "ts": "github:frankwallis/plugin-typescript@4.0.10",
    "typescript": "npm:typescript@1.8.10",
    "zone.js": "npm:zone.js@0.6.12",
    "github:frankwallis/plugin-typescript@4.0.10": {
      "typescript": "npm:typescript@1.8.10"
    },
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.3.0"
    },
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.6.0"
    },
    "github:jspm/nodelibs-os@0.1.0": {
      "os-browserify": "npm:os-browserify@0.1.2"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.3"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:angular2@2.0.0-beta.17": {
      "reflect-metadata": "npm:reflect-metadata@0.1.2",
      "rxjs": "npm:rxjs@5.0.0-beta.7",
      "zone.js": "npm:zone.js@0.6.12"
    },
    "npm:assert@1.3.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:buffer@3.6.0": {
      "base64-js": "npm:base64-js@0.0.8",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "ieee754": "npm:ieee754@1.1.6",
      "isarray": "npm:isarray@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:os-browserify@0.1.2": {
      "os": "github:jspm/nodelibs-os@0.1.0"
    },
    "npm:process@0.11.3": {
      "assert": "github:jspm/nodelibs-assert@0.1.0"
    },
    "npm:reflect-metadata@0.1.2": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:rxjs@5.0.0-beta.7": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "symbol-observable": "npm:symbol-observable@0.2.4"
    },
    "npm:typescript@1.8.10": {
      "os": "github:jspm/nodelibs-os@0.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:zone.js@0.6.12": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    }
  }
});
